/*
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,states.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
root                      ::= coverage

coverage                  ::= (simple_coverage | tiered_coverage) (space pipe space coverage_modifier)?
tiered_coverage           ::= tier (space slash space tier)*
tier                      ::= tier_name colon space (tier_coverage | not_applicable)
tier_coverage             ::= simple_coverage (space (then | or | and) space simple_coverage)* tier_limitation?
simple_coverage           ::= (pre_coverage_limitation space)? coverage_amount (space post_coverage_limitation)? (comma? space coverage_condition)?
coverage_modifier         ::= limit_condition colon space (((simple_coverage | simple_limitation) (semicolon space see_carrier_documentation)?) | see_carrier_documentation | waived_if_admitted | shared_across_tiers)
waived_if_admitted        ::= ("copay" space)? "waived if admitted"
simple_limitation         ::= pre_coverage_limitation space "copay applies"
tier_name                 ::= "In-Network-Tier-2" | "Out-of-Network" | "In-Network"
limit_condition           ::= "limit" | "condition"
tier_limitation           ::= comma space "up to" space (currency | (integer space time_unit plural?)) (space post_coverage_limitation)?
coverage_amount           ::= currency | unlimited | included | unknown | percentage | (digits space (treatment_unit | time_unit) plural?)
pre_coverage_limitation   ::= first space digits space time_unit plural?
post_coverage_limitation  ::= (((then space currency) | "per condition") space)? "per" space (treatment_unit | (integer space time_unit) | time_unit) plural?
coverage_condition        ::= ("before deductible" | "after deductible" | "penalty" | allowance | "in-state" | "out-of-state") (space allowance)?
allowance                 ::= upto_allowance | after_allowance
upto_allowance            ::= "up to" space (currency space)? "allowance"
after_allowance           ::= "after" space (currency space)? "allowance"
see_carrier_documentation ::= "see carrier documentation for more information"
shared_across_tiers       ::= "shared across all tiers"
unknown                   ::= "unknown"
unlimited                 ::= /[uU]nlimited/
included                  ::= /[iI]ncluded in [mM]edical/
time_unit                 ::= /[hH]our/ | (((/[cC]alendar/ | /[cC]ontract/) space)? /[yY]ear/) | /[mM]onth/ | /[dD]ay/ | /[wW]eek/ | /[vV]isit/ | /[lL]ifetime/ | ((((/[bB]enefit/ plural?) | /[eE]ligibility/) space)? /[pP]eriod/)
treatment_unit            ::= /[pP]erson/ | /[gG]roup/ | /[cC]ondition/ | /[sS]cript/ | /[vV]isit/ | /[eE]xam/ | /[iI]tem/ | /[sS]tay/ | /[tT]reatment/ | /[aA]dmission/ | /[eE]pisode/
comma                     ::= ","
colon                     ::= ":"
semicolon                 ::= ";"
pipe                      ::= "|"
slash                     ::= "/"
plural                    ::= "(s)" | "s"
then                      ::= "then" | ("," space) | space
or                        ::= "or"
and                       ::= "and"
not_applicable            ::= "Not Applicable" | "N/A" | "NA"
first                     ::= "first"
currency                  ::= "$" number
percentage                ::= number "%"
number                    ::= float | integer
float                     ::= digits "." digits
integer                   ::= /[0-9]/+ (comma_int | under_int)*
comma_int                 ::= ("," /[0-9]/*3) !"_"
under_int                 ::= ("_" /[0-9]/*3) !","
digits                    ::= /[0-9]/+ ("_" /[0-9]/+)*
space                     ::= /[ \t]/+
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import model.PlanIdentifier;

import java.io.Serializable;
/**
 * ACAPlan2018
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-02T17:06:11.296-04:00")
public class ACAPlan2018  implements Serializable {
  @JsonProperty("carrier_name")
  private String carrierName = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("effective_date")
  private String effectiveDate = null;

  @JsonProperty("expiration_date")
  private String expirationDate = null;

  @JsonProperty("identifiers")
  private List<PlanIdentifier> identifiers = new ArrayList<PlanIdentifier>();

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("network_ids")
  private List<Integer> networkIds = new ArrayList<Integer>();

  @JsonProperty("network_size")
  private Integer networkSize = null;

  @JsonProperty("plan_type")
  private String planType = null;

  @JsonProperty("service_area_id")
  private String serviceAreaId = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("adult_dental")
  private Boolean adultDental = null;

  @JsonProperty("age29_rider")
  private Boolean age29Rider = null;

  @JsonProperty("ambulance")
  private String ambulance = null;

  @JsonProperty("benefits_summary_url")
  private String benefitsSummaryUrl = null;

  @JsonProperty("buy_link")
  private String buyLink = null;

  @JsonProperty("child_dental")
  private Boolean childDental = null;

  @JsonProperty("child_eyewear")
  private String childEyewear = null;

  @JsonProperty("child_eye_exam")
  private String childEyeExam = null;

  @JsonProperty("customer_service_phone_number")
  private String customerServicePhoneNumber = null;

  @JsonProperty("durable_medical_equipment")
  private String durableMedicalEquipment = null;

  @JsonProperty("diagnostic_test")
  private String diagnosticTest = null;

  @JsonProperty("dp_rider")
  private Boolean dpRider = null;

  @JsonProperty("drug_formulary_url")
  private String drugFormularyUrl = null;

  @JsonProperty("emergency_room")
  private String emergencyRoom = null;

  @JsonProperty("family_drug_deductible")
  private String familyDrugDeductible = null;

  @JsonProperty("family_drug_moop")
  private String familyDrugMoop = null;

  @JsonProperty("family_medical_deductible")
  private String familyMedicalDeductible = null;

  @JsonProperty("family_medical_moop")
  private String familyMedicalMoop = null;

  @JsonProperty("fp_rider")
  private Boolean fpRider = null;

  @JsonProperty("generic_drugs")
  private String genericDrugs = null;

  @JsonProperty("habilitation_services")
  private String habilitationServices = null;

  @JsonProperty("hios_issuer_id")
  private String hiosIssuerId = null;

  @JsonProperty("home_health_care")
  private String homeHealthCare = null;

  @JsonProperty("hospice_service")
  private String hospiceService = null;

  @JsonProperty("hsa_eligible")
  private Boolean hsaEligible = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("imaging")
  private String imaging = null;

  @JsonProperty("individual_drug_deductible")
  private String individualDrugDeductible = null;

  @JsonProperty("individual_drug_moop")
  private String individualDrugMoop = null;

  @JsonProperty("individual_medical_deductible")
  private String individualMedicalDeductible = null;

  @JsonProperty("individual_medical_moop")
  private String individualMedicalMoop = null;

  @JsonProperty("inpatient_birth")
  private String inpatientBirth = null;

  @JsonProperty("inpatient_facility")
  private String inpatientFacility = null;

  @JsonProperty("inpatient_mental_health")
  private String inpatientMentalHealth = null;

  @JsonProperty("inpatient_physician")
  private String inpatientPhysician = null;

  @JsonProperty("inpatient_substance")
  private String inpatientSubstance = null;

  @JsonProperty("in_network_ids")
  private List<Integer> inNetworkIds = new ArrayList<Integer>();

  @JsonProperty("level")
  private String level = null;

  @JsonProperty("logo_url")
  private String logoUrl = null;

  @JsonProperty("non_preferred_brand_drugs")
  private String nonPreferredBrandDrugs = null;

  @JsonProperty("on_market")
  private Boolean onMarket = null;

  @JsonProperty("off_market")
  private Boolean offMarket = null;

  @JsonProperty("out_of_network_coverage")
  private Boolean outOfNetworkCoverage = null;

  @JsonProperty("out_of_network_ids")
  private List<Integer> outOfNetworkIds = new ArrayList<Integer>();

  @JsonProperty("outpatient_facility")
  private String outpatientFacility = null;

  @JsonProperty("outpatient_mental_health")
  private String outpatientMentalHealth = null;

  @JsonProperty("outpatient_physician")
  private String outpatientPhysician = null;

  @JsonProperty("outpatient_substance")
  private String outpatientSubstance = null;

  @JsonProperty("plan_market")
  private String planMarket = null;

  @JsonProperty("preferred_brand_drugs")
  private String preferredBrandDrugs = null;

  @JsonProperty("prenatal_postnatal_care")
  private String prenatalPostnatalCare = null;

  @JsonProperty("preventative_care")
  private String preventativeCare = null;

  @JsonProperty("premium_subsidized")
  private BigDecimal premiumSubsidized = null;

  @JsonProperty("premium")
  private BigDecimal premium = null;

  @JsonProperty("premium_source")
  private String premiumSource = null;

  @JsonProperty("primary_care_physician")
  private String primaryCarePhysician = null;

  @JsonProperty("rehabilitation_services")
  private String rehabilitationServices = null;

  @JsonProperty("skilled_nursing")
  private String skilledNursing = null;

  @JsonProperty("specialist")
  private String specialist = null;

  @JsonProperty("specialty_drugs")
  private String specialtyDrugs = null;

  @JsonProperty("urgent_care")
  private String urgentCare = null;

  @JsonProperty("actuarial_value")
  private BigDecimal actuarialValue = null;

  @JsonProperty("chiropractic_services")
  private String chiropracticServices = null;

  @JsonProperty("coinsurance")
  private BigDecimal coinsurance = null;

  @JsonProperty("embedded_deductible")
  private String embeddedDeductible = null;

  @JsonProperty("gated")
  private Boolean gated = null;

  @JsonProperty("imaging_center")
  private String imagingCenter = null;

  @JsonProperty("imaging_physician")
  private String imagingPhysician = null;

  @JsonProperty("lab_test")
  private String labTest = null;

  @JsonProperty("mail_order_rx")
  private BigDecimal mailOrderRx = null;

  @JsonProperty("nonpreferred_generic_drug_share")
  private String nonpreferredGenericDrugShare = null;

  @JsonProperty("nonpreferred_specialty_drug_share")
  private String nonpreferredSpecialtyDrugShare = null;

  @JsonProperty("outpatient_ambulatory_care_center")
  private String outpatientAmbulatoryCareCenter = null;

  @JsonProperty("plan_calendar")
  private String planCalendar = null;

  @JsonProperty("prenatal_care")
  private String prenatalCare = null;

  @JsonProperty("postnatal_care")
  private String postnatalCare = null;

  @JsonProperty("skilled_nursing_facility_365")
  private String skilledNursingFacility365 = null;

  public ACAPlan2018 carrierName(String carrierName) {
    this.carrierName = carrierName;
    return this;
  }

   /**
   * Name of the insurance carrier
   * @return carrierName
  **/
  @ApiModelProperty(example = "null", value = "Name of the insurance carrier")
  public String getCarrierName() {
    return carrierName;
  }

  public void setCarrierName(String carrierName) {
    this.carrierName = carrierName;
  }

  public ACAPlan2018 displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Alternate name for the Plan
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "Alternate name for the Plan")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ACAPlan2018 effectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Effective date of coverage.
   * @return effectiveDate
  **/
  @ApiModelProperty(example = "null", value = "Effective date of coverage.")
  public String getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public ACAPlan2018 expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Expiration date of coverage.
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", value = "Expiration date of coverage.")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public ACAPlan2018 identifiers(List<PlanIdentifier> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public ACAPlan2018 addIdentifiersItem(PlanIdentifier identifiersItem) {
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * List of identifiers of this Plan
   * @return identifiers
  **/
  @ApiModelProperty(example = "null", value = "List of identifiers of this Plan")
  public List<PlanIdentifier> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(List<PlanIdentifier> identifiers) {
    this.identifiers = identifiers;
  }

  public ACAPlan2018 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Marketing name of the plan
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Marketing name of the plan")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ACAPlan2018 networkIds(List<Integer> networkIds) {
    this.networkIds = networkIds;
    return this;
  }

  public ACAPlan2018 addNetworkIdsItem(Integer networkIdsItem) {
    this.networkIds.add(networkIdsItem);
    return this;
  }

   /**
   * List of Vericred-generated network_ids
   * @return networkIds
  **/
  @ApiModelProperty(example = "null", value = "List of Vericred-generated network_ids")
  public List<Integer> getNetworkIds() {
    return networkIds;
  }

  public void setNetworkIds(List<Integer> networkIds) {
    this.networkIds = networkIds;
  }

  public ACAPlan2018 networkSize(Integer networkSize) {
    this.networkSize = networkSize;
    return this;
  }

   /**
   * Total number of Providers in network
   * @return networkSize
  **/
  @ApiModelProperty(example = "null", value = "Total number of Providers in network")
  public Integer getNetworkSize() {
    return networkSize;
  }

  public void setNetworkSize(Integer networkSize) {
    this.networkSize = networkSize;
  }

  public ACAPlan2018 planType(String planType) {
    this.planType = planType;
    return this;
  }

   /**
   * Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity, PACE, Medicare-Medicaid, HMO w/POS, Cost, FFS, MSA)
   * @return planType
  **/
  @ApiModelProperty(example = "null", value = "Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity, PACE, Medicare-Medicaid, HMO w/POS, Cost, FFS, MSA)")
  public String getPlanType() {
    return planType;
  }

  public void setPlanType(String planType) {
    this.planType = planType;
  }

  public ACAPlan2018 serviceAreaId(String serviceAreaId) {
    this.serviceAreaId = serviceAreaId;
    return this;
  }

   /**
   * Foreign key for service area
   * @return serviceAreaId
  **/
  @ApiModelProperty(example = "null", value = "Foreign key for service area")
  public String getServiceAreaId() {
    return serviceAreaId;
  }

  public void setServiceAreaId(String serviceAreaId) {
    this.serviceAreaId = serviceAreaId;
  }

  public ACAPlan2018 source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Source of the plan benefit data
   * @return source
  **/
  @ApiModelProperty(example = "null", value = "Source of the plan benefit data")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public ACAPlan2018 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the Plan
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "The type of the Plan")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ACAPlan2018 adultDental(Boolean adultDental) {
    this.adultDental = adultDental;
    return this;
  }

   /**
   * Does the plan provide dental coverage for adults?
   * @return adultDental
  **/
  @ApiModelProperty(example = "null", value = "Does the plan provide dental coverage for adults?")
  public Boolean getAdultDental() {
    return adultDental;
  }

  public void setAdultDental(Boolean adultDental) {
    this.adultDental = adultDental;
  }

  public ACAPlan2018 age29Rider(Boolean age29Rider) {
    this.age29Rider = age29Rider;
    return this;
  }

   /**
   * True if the plan allows dependents up to age 29
   * @return age29Rider
  **/
  @ApiModelProperty(example = "null", value = "True if the plan allows dependents up to age 29")
  public Boolean getAge29Rider() {
    return age29Rider;
  }

  public void setAge29Rider(Boolean age29Rider) {
    this.age29Rider = age29Rider;
  }

  public ACAPlan2018 ambulance(String ambulance) {
    this.ambulance = ambulance;
    return this;
  }

   /**
   * Benefits string for ambulance coverage
   * @return ambulance
  **/
  @ApiModelProperty(example = "null", value = "Benefits string for ambulance coverage")
  public String getAmbulance() {
    return ambulance;
  }

  public void setAmbulance(String ambulance) {
    this.ambulance = ambulance;
  }

  public ACAPlan2018 benefitsSummaryUrl(String benefitsSummaryUrl) {
    this.benefitsSummaryUrl = benefitsSummaryUrl;
    return this;
  }

   /**
   * Link to the summary of benefits and coverage (SBC) document.
   * @return benefitsSummaryUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to the summary of benefits and coverage (SBC) document.")
  public String getBenefitsSummaryUrl() {
    return benefitsSummaryUrl;
  }

  public void setBenefitsSummaryUrl(String benefitsSummaryUrl) {
    this.benefitsSummaryUrl = benefitsSummaryUrl;
  }

  public ACAPlan2018 buyLink(String buyLink) {
    this.buyLink = buyLink;
    return this;
  }

   /**
   * Link to a location to purchase the plan.
   * @return buyLink
  **/
  @ApiModelProperty(example = "null", value = "Link to a location to purchase the plan.")
  public String getBuyLink() {
    return buyLink;
  }

  public void setBuyLink(String buyLink) {
    this.buyLink = buyLink;
  }

  public ACAPlan2018 childDental(Boolean childDental) {
    this.childDental = childDental;
    return this;
  }

   /**
   * Does the plan provide dental coverage for children?
   * @return childDental
  **/
  @ApiModelProperty(example = "null", value = "Does the plan provide dental coverage for children?")
  public Boolean getChildDental() {
    return childDental;
  }

  public void setChildDental(Boolean childDental) {
    this.childDental = childDental;
  }

  public ACAPlan2018 childEyewear(String childEyewear) {
    this.childEyewear = childEyewear;
    return this;
  }

   /**
   * Child eyewear benefits summary
   * @return childEyewear
  **/
  @ApiModelProperty(example = "null", value = "Child eyewear benefits summary")
  public String getChildEyewear() {
    return childEyewear;
  }

  public void setChildEyewear(String childEyewear) {
    this.childEyewear = childEyewear;
  }

  public ACAPlan2018 childEyeExam(String childEyeExam) {
    this.childEyeExam = childEyeExam;
    return this;
  }

   /**
   * Child eye exam benefits summary
   * @return childEyeExam
  **/
  @ApiModelProperty(example = "null", value = "Child eye exam benefits summary")
  public String getChildEyeExam() {
    return childEyeExam;
  }

  public void setChildEyeExam(String childEyeExam) {
    this.childEyeExam = childEyeExam;
  }

  public ACAPlan2018 customerServicePhoneNumber(String customerServicePhoneNumber) {
    this.customerServicePhoneNumber = customerServicePhoneNumber;
    return this;
  }

   /**
   * Phone number to contact the insurance carrier
   * @return customerServicePhoneNumber
  **/
  @ApiModelProperty(example = "null", value = "Phone number to contact the insurance carrier")
  public String getCustomerServicePhoneNumber() {
    return customerServicePhoneNumber;
  }

  public void setCustomerServicePhoneNumber(String customerServicePhoneNumber) {
    this.customerServicePhoneNumber = customerServicePhoneNumber;
  }

  public ACAPlan2018 durableMedicalEquipment(String durableMedicalEquipment) {
    this.durableMedicalEquipment = durableMedicalEquipment;
    return this;
  }

   /**
   * Benefits summary for durable medical equipment
   * @return durableMedicalEquipment
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for durable medical equipment")
  public String getDurableMedicalEquipment() {
    return durableMedicalEquipment;
  }

  public void setDurableMedicalEquipment(String durableMedicalEquipment) {
    this.durableMedicalEquipment = durableMedicalEquipment;
  }

  public ACAPlan2018 diagnosticTest(String diagnosticTest) {
    this.diagnosticTest = diagnosticTest;
    return this;
  }

   /**
   * Diagnostic tests benefit summary
   * @return diagnosticTest
  **/
  @ApiModelProperty(example = "null", value = "Diagnostic tests benefit summary")
  public String getDiagnosticTest() {
    return diagnosticTest;
  }

  public void setDiagnosticTest(String diagnosticTest) {
    this.diagnosticTest = diagnosticTest;
  }

  public ACAPlan2018 dpRider(Boolean dpRider) {
    this.dpRider = dpRider;
    return this;
  }

   /**
   * True if plan does not cover domestic partners
   * @return dpRider
  **/
  @ApiModelProperty(example = "null", value = "True if plan does not cover domestic partners")
  public Boolean getDpRider() {
    return dpRider;
  }

  public void setDpRider(Boolean dpRider) {
    this.dpRider = dpRider;
  }

  public ACAPlan2018 drugFormularyUrl(String drugFormularyUrl) {
    this.drugFormularyUrl = drugFormularyUrl;
    return this;
  }

   /**
   * Link to the summary of drug benefits for the plan
   * @return drugFormularyUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to the summary of drug benefits for the plan")
  public String getDrugFormularyUrl() {
    return drugFormularyUrl;
  }

  public void setDrugFormularyUrl(String drugFormularyUrl) {
    this.drugFormularyUrl = drugFormularyUrl;
  }

  public ACAPlan2018 emergencyRoom(String emergencyRoom) {
    this.emergencyRoom = emergencyRoom;
    return this;
  }

   /**
   * Description of costs when visiting the ER
   * @return emergencyRoom
  **/
  @ApiModelProperty(example = "null", value = "Description of costs when visiting the ER")
  public String getEmergencyRoom() {
    return emergencyRoom;
  }

  public void setEmergencyRoom(String emergencyRoom) {
    this.emergencyRoom = emergencyRoom;
  }

  public ACAPlan2018 familyDrugDeductible(String familyDrugDeductible) {
    this.familyDrugDeductible = familyDrugDeductible;
    return this;
  }

   /**
   * Deductible for drugs when a family is on the plan.
   * @return familyDrugDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible for drugs when a family is on the plan.")
  public String getFamilyDrugDeductible() {
    return familyDrugDeductible;
  }

  public void setFamilyDrugDeductible(String familyDrugDeductible) {
    this.familyDrugDeductible = familyDrugDeductible;
  }

  public ACAPlan2018 familyDrugMoop(String familyDrugMoop) {
    this.familyDrugMoop = familyDrugMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket for drugs when a family is on the plan
   * @return familyDrugMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket for drugs when a family is on the plan")
  public String getFamilyDrugMoop() {
    return familyDrugMoop;
  }

  public void setFamilyDrugMoop(String familyDrugMoop) {
    this.familyDrugMoop = familyDrugMoop;
  }

  public ACAPlan2018 familyMedicalDeductible(String familyMedicalDeductible) {
    this.familyMedicalDeductible = familyMedicalDeductible;
    return this;
  }

   /**
   * Deductible when a family is on the plan
   * @return familyMedicalDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible when a family is on the plan")
  public String getFamilyMedicalDeductible() {
    return familyMedicalDeductible;
  }

  public void setFamilyMedicalDeductible(String familyMedicalDeductible) {
    this.familyMedicalDeductible = familyMedicalDeductible;
  }

  public ACAPlan2018 familyMedicalMoop(String familyMedicalMoop) {
    this.familyMedicalMoop = familyMedicalMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket when a family is on the plan
   * @return familyMedicalMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket when a family is on the plan")
  public String getFamilyMedicalMoop() {
    return familyMedicalMoop;
  }

  public void setFamilyMedicalMoop(String familyMedicalMoop) {
    this.familyMedicalMoop = familyMedicalMoop;
  }

  public ACAPlan2018 fpRider(Boolean fpRider) {
    this.fpRider = fpRider;
    return this;
  }

   /**
   * True if plan does not cover family planning
   * @return fpRider
  **/
  @ApiModelProperty(example = "null", value = "True if plan does not cover family planning")
  public Boolean getFpRider() {
    return fpRider;
  }

  public void setFpRider(Boolean fpRider) {
    this.fpRider = fpRider;
  }

  public ACAPlan2018 genericDrugs(String genericDrugs) {
    this.genericDrugs = genericDrugs;
    return this;
  }

   /**
   * Cost for generic drugs
   * @return genericDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost for generic drugs")
  public String getGenericDrugs() {
    return genericDrugs;
  }

  public void setGenericDrugs(String genericDrugs) {
    this.genericDrugs = genericDrugs;
  }

  public ACAPlan2018 habilitationServices(String habilitationServices) {
    this.habilitationServices = habilitationServices;
    return this;
  }

   /**
   * Habilitation services benefits summary
   * @return habilitationServices
  **/
  @ApiModelProperty(example = "null", value = "Habilitation services benefits summary")
  public String getHabilitationServices() {
    return habilitationServices;
  }

  public void setHabilitationServices(String habilitationServices) {
    this.habilitationServices = habilitationServices;
  }

  public ACAPlan2018 hiosIssuerId(String hiosIssuerId) {
    this.hiosIssuerId = hiosIssuerId;
    return this;
  }

   /**
   * 
   * @return hiosIssuerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHiosIssuerId() {
    return hiosIssuerId;
  }

  public void setHiosIssuerId(String hiosIssuerId) {
    this.hiosIssuerId = hiosIssuerId;
  }

  public ACAPlan2018 homeHealthCare(String homeHealthCare) {
    this.homeHealthCare = homeHealthCare;
    return this;
  }

   /**
   * Home health care benefits summary
   * @return homeHealthCare
  **/
  @ApiModelProperty(example = "null", value = "Home health care benefits summary")
  public String getHomeHealthCare() {
    return homeHealthCare;
  }

  public void setHomeHealthCare(String homeHealthCare) {
    this.homeHealthCare = homeHealthCare;
  }

  public ACAPlan2018 hospiceService(String hospiceService) {
    this.hospiceService = hospiceService;
    return this;
  }

   /**
   * Hospice service benefits summary
   * @return hospiceService
  **/
  @ApiModelProperty(example = "null", value = "Hospice service benefits summary")
  public String getHospiceService() {
    return hospiceService;
  }

  public void setHospiceService(String hospiceService) {
    this.hospiceService = hospiceService;
  }

  public ACAPlan2018 hsaEligible(Boolean hsaEligible) {
    this.hsaEligible = hsaEligible;
    return this;
  }

   /**
   * Is the plan HSA eligible?
   * @return hsaEligible
  **/
  @ApiModelProperty(example = "null", value = "Is the plan HSA eligible?")
  public Boolean getHsaEligible() {
    return hsaEligible;
  }

  public void setHsaEligible(Boolean hsaEligible) {
    this.hsaEligible = hsaEligible;
  }

  public ACAPlan2018 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Government-issued HIOS plan ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Government-issued HIOS plan ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ACAPlan2018 imaging(String imaging) {
    this.imaging = imaging;
    return this;
  }

   /**
   * Benefits summary for imaging coverage
   * @return imaging
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for imaging coverage")
  public String getImaging() {
    return imaging;
  }

  public void setImaging(String imaging) {
    this.imaging = imaging;
  }

  public ACAPlan2018 individualDrugDeductible(String individualDrugDeductible) {
    this.individualDrugDeductible = individualDrugDeductible;
    return this;
  }

   /**
   * Deductible for drugs when an individual is on the plan
   * @return individualDrugDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible for drugs when an individual is on the plan")
  public String getIndividualDrugDeductible() {
    return individualDrugDeductible;
  }

  public void setIndividualDrugDeductible(String individualDrugDeductible) {
    this.individualDrugDeductible = individualDrugDeductible;
  }

  public ACAPlan2018 individualDrugMoop(String individualDrugMoop) {
    this.individualDrugMoop = individualDrugMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket for drugs when an individual is on the plan
   * @return individualDrugMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket for drugs when an individual is on the plan")
  public String getIndividualDrugMoop() {
    return individualDrugMoop;
  }

  public void setIndividualDrugMoop(String individualDrugMoop) {
    this.individualDrugMoop = individualDrugMoop;
  }

  public ACAPlan2018 individualMedicalDeductible(String individualMedicalDeductible) {
    this.individualMedicalDeductible = individualMedicalDeductible;
    return this;
  }

   /**
   * Deductible when an individual is on the plan
   * @return individualMedicalDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible when an individual is on the plan")
  public String getIndividualMedicalDeductible() {
    return individualMedicalDeductible;
  }

  public void setIndividualMedicalDeductible(String individualMedicalDeductible) {
    this.individualMedicalDeductible = individualMedicalDeductible;
  }

  public ACAPlan2018 individualMedicalMoop(String individualMedicalMoop) {
    this.individualMedicalMoop = individualMedicalMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket when an individual is on the plan
   * @return individualMedicalMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket when an individual is on the plan")
  public String getIndividualMedicalMoop() {
    return individualMedicalMoop;
  }

  public void setIndividualMedicalMoop(String individualMedicalMoop) {
    this.individualMedicalMoop = individualMedicalMoop;
  }

  public ACAPlan2018 inpatientBirth(String inpatientBirth) {
    this.inpatientBirth = inpatientBirth;
    return this;
  }

   /**
   * Inpatient birth benefits summary
   * @return inpatientBirth
  **/
  @ApiModelProperty(example = "null", value = "Inpatient birth benefits summary")
  public String getInpatientBirth() {
    return inpatientBirth;
  }

  public void setInpatientBirth(String inpatientBirth) {
    this.inpatientBirth = inpatientBirth;
  }

  public ACAPlan2018 inpatientFacility(String inpatientFacility) {
    this.inpatientFacility = inpatientFacility;
    return this;
  }

   /**
   * Cost under the plan for an inpatient facility
   * @return inpatientFacility
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for an inpatient facility")
  public String getInpatientFacility() {
    return inpatientFacility;
  }

  public void setInpatientFacility(String inpatientFacility) {
    this.inpatientFacility = inpatientFacility;
  }

  public ACAPlan2018 inpatientMentalHealth(String inpatientMentalHealth) {
    this.inpatientMentalHealth = inpatientMentalHealth;
    return this;
  }

   /**
   * Inpatient mental helath benefits summary
   * @return inpatientMentalHealth
  **/
  @ApiModelProperty(example = "null", value = "Inpatient mental helath benefits summary")
  public String getInpatientMentalHealth() {
    return inpatientMentalHealth;
  }

  public void setInpatientMentalHealth(String inpatientMentalHealth) {
    this.inpatientMentalHealth = inpatientMentalHealth;
  }

  public ACAPlan2018 inpatientPhysician(String inpatientPhysician) {
    this.inpatientPhysician = inpatientPhysician;
    return this;
  }

   /**
   * Cost under the plan for an inpatient physician
   * @return inpatientPhysician
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for an inpatient physician")
  public String getInpatientPhysician() {
    return inpatientPhysician;
  }

  public void setInpatientPhysician(String inpatientPhysician) {
    this.inpatientPhysician = inpatientPhysician;
  }

  public ACAPlan2018 inpatientSubstance(String inpatientSubstance) {
    this.inpatientSubstance = inpatientSubstance;
    return this;
  }

   /**
   * Inpatient substance abuse benefits summary
   * @return inpatientSubstance
  **/
  @ApiModelProperty(example = "null", value = "Inpatient substance abuse benefits summary")
  public String getInpatientSubstance() {
    return inpatientSubstance;
  }

  public void setInpatientSubstance(String inpatientSubstance) {
    this.inpatientSubstance = inpatientSubstance;
  }

  public ACAPlan2018 inNetworkIds(List<Integer> inNetworkIds) {
    this.inNetworkIds = inNetworkIds;
    return this;
  }

  public ACAPlan2018 addInNetworkIdsItem(Integer inNetworkIdsItem) {
    this.inNetworkIds.add(inNetworkIdsItem);
    return this;
  }

   /**
   * List of NPI numbers for Providers passed in who accept this Plan
   * @return inNetworkIds
  **/
  @ApiModelProperty(example = "null", value = "List of NPI numbers for Providers passed in who accept this Plan")
  public List<Integer> getInNetworkIds() {
    return inNetworkIds;
  }

  public void setInNetworkIds(List<Integer> inNetworkIds) {
    this.inNetworkIds = inNetworkIds;
  }

  public ACAPlan2018 level(String level) {
    this.level = level;
    return this;
  }

   /**
   * Plan metal grouping (e.g. platinum, gold, silver, etc)
   * @return level
  **/
  @ApiModelProperty(example = "null", value = "Plan metal grouping (e.g. platinum, gold, silver, etc)")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public ACAPlan2018 logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Link to a copy of the insurance carrier's logo
   * @return logoUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to a copy of the insurance carrier's logo")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public ACAPlan2018 nonPreferredBrandDrugs(String nonPreferredBrandDrugs) {
    this.nonPreferredBrandDrugs = nonPreferredBrandDrugs;
    return this;
  }

   /**
   * Cost under the plan for non-preferred brand drugs
   * @return nonPreferredBrandDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for non-preferred brand drugs")
  public String getNonPreferredBrandDrugs() {
    return nonPreferredBrandDrugs;
  }

  public void setNonPreferredBrandDrugs(String nonPreferredBrandDrugs) {
    this.nonPreferredBrandDrugs = nonPreferredBrandDrugs;
  }

  public ACAPlan2018 onMarket(Boolean onMarket) {
    this.onMarket = onMarket;
    return this;
  }

   /**
   * Is the plan on-market?
   * @return onMarket
  **/
  @ApiModelProperty(example = "null", value = "Is the plan on-market?")
  public Boolean getOnMarket() {
    return onMarket;
  }

  public void setOnMarket(Boolean onMarket) {
    this.onMarket = onMarket;
  }

  public ACAPlan2018 offMarket(Boolean offMarket) {
    this.offMarket = offMarket;
    return this;
  }

   /**
   * Is the plan off-market?
   * @return offMarket
  **/
  @ApiModelProperty(example = "null", value = "Is the plan off-market?")
  public Boolean getOffMarket() {
    return offMarket;
  }

  public void setOffMarket(Boolean offMarket) {
    this.offMarket = offMarket;
  }

  public ACAPlan2018 outOfNetworkCoverage(Boolean outOfNetworkCoverage) {
    this.outOfNetworkCoverage = outOfNetworkCoverage;
    return this;
  }

   /**
   * Does this plan provide any out of network coverage?
   * @return outOfNetworkCoverage
  **/
  @ApiModelProperty(example = "null", value = "Does this plan provide any out of network coverage?")
  public Boolean getOutOfNetworkCoverage() {
    return outOfNetworkCoverage;
  }

  public void setOutOfNetworkCoverage(Boolean outOfNetworkCoverage) {
    this.outOfNetworkCoverage = outOfNetworkCoverage;
  }

  public ACAPlan2018 outOfNetworkIds(List<Integer> outOfNetworkIds) {
    this.outOfNetworkIds = outOfNetworkIds;
    return this;
  }

  public ACAPlan2018 addOutOfNetworkIdsItem(Integer outOfNetworkIdsItem) {
    this.outOfNetworkIds.add(outOfNetworkIdsItem);
    return this;
  }

   /**
   * List of NPI numbers for Providers passed in who do not accept this Plan
   * @return outOfNetworkIds
  **/
  @ApiModelProperty(example = "null", value = "List of NPI numbers for Providers passed in who do not accept this Plan")
  public List<Integer> getOutOfNetworkIds() {
    return outOfNetworkIds;
  }

  public void setOutOfNetworkIds(List<Integer> outOfNetworkIds) {
    this.outOfNetworkIds = outOfNetworkIds;
  }

  public ACAPlan2018 outpatientFacility(String outpatientFacility) {
    this.outpatientFacility = outpatientFacility;
    return this;
  }

   /**
   * Benefits summary for outpatient facility coverage
   * @return outpatientFacility
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient facility coverage")
  public String getOutpatientFacility() {
    return outpatientFacility;
  }

  public void setOutpatientFacility(String outpatientFacility) {
    this.outpatientFacility = outpatientFacility;
  }

  public ACAPlan2018 outpatientMentalHealth(String outpatientMentalHealth) {
    this.outpatientMentalHealth = outpatientMentalHealth;
    return this;
  }

   /**
   * Benefits summary for outpatient mental health coverage
   * @return outpatientMentalHealth
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient mental health coverage")
  public String getOutpatientMentalHealth() {
    return outpatientMentalHealth;
  }

  public void setOutpatientMentalHealth(String outpatientMentalHealth) {
    this.outpatientMentalHealth = outpatientMentalHealth;
  }

  public ACAPlan2018 outpatientPhysician(String outpatientPhysician) {
    this.outpatientPhysician = outpatientPhysician;
    return this;
  }

   /**
   * Benefits summary for outpatient physician coverage
   * @return outpatientPhysician
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient physician coverage")
  public String getOutpatientPhysician() {
    return outpatientPhysician;
  }

  public void setOutpatientPhysician(String outpatientPhysician) {
    this.outpatientPhysician = outpatientPhysician;
  }

  public ACAPlan2018 outpatientSubstance(String outpatientSubstance) {
    this.outpatientSubstance = outpatientSubstance;
    return this;
  }

   /**
   * Outpatient substance abuse benefits summary
   * @return outpatientSubstance
  **/
  @ApiModelProperty(example = "null", value = "Outpatient substance abuse benefits summary")
  public String getOutpatientSubstance() {
    return outpatientSubstance;
  }

  public void setOutpatientSubstance(String outpatientSubstance) {
    this.outpatientSubstance = outpatientSubstance;
  }

  public ACAPlan2018 planMarket(String planMarket) {
    this.planMarket = planMarket;
    return this;
  }

   /**
   * Market in which the plan is offered (on_marketplace, shop, etc)
   * @return planMarket
  **/
  @ApiModelProperty(example = "null", value = "Market in which the plan is offered (on_marketplace, shop, etc)")
  public String getPlanMarket() {
    return planMarket;
  }

  public void setPlanMarket(String planMarket) {
    this.planMarket = planMarket;
  }

  public ACAPlan2018 preferredBrandDrugs(String preferredBrandDrugs) {
    this.preferredBrandDrugs = preferredBrandDrugs;
    return this;
  }

   /**
   * Cost under the plan for perferred brand drugs
   * @return preferredBrandDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for perferred brand drugs")
  public String getPreferredBrandDrugs() {
    return preferredBrandDrugs;
  }

  public void setPreferredBrandDrugs(String preferredBrandDrugs) {
    this.preferredBrandDrugs = preferredBrandDrugs;
  }

  public ACAPlan2018 prenatalPostnatalCare(String prenatalPostnatalCare) {
    this.prenatalPostnatalCare = prenatalPostnatalCare;
    return this;
  }

   /**
   * Inpatient substance abuse benefits summary
   * @return prenatalPostnatalCare
  **/
  @ApiModelProperty(example = "null", value = "Inpatient substance abuse benefits summary")
  public String getPrenatalPostnatalCare() {
    return prenatalPostnatalCare;
  }

  public void setPrenatalPostnatalCare(String prenatalPostnatalCare) {
    this.prenatalPostnatalCare = prenatalPostnatalCare;
  }

  public ACAPlan2018 preventativeCare(String preventativeCare) {
    this.preventativeCare = preventativeCare;
    return this;
  }

   /**
   * Benefits summary for preventative care
   * @return preventativeCare
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for preventative care")
  public String getPreventativeCare() {
    return preventativeCare;
  }

  public void setPreventativeCare(String preventativeCare) {
    this.preventativeCare = preventativeCare;
  }

  public ACAPlan2018 premiumSubsidized(BigDecimal premiumSubsidized) {
    this.premiumSubsidized = premiumSubsidized;
    return this;
  }

   /**
   * Cumulative premium amount after subsidy
   * @return premiumSubsidized
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount after subsidy")
  public BigDecimal getPremiumSubsidized() {
    return premiumSubsidized;
  }

  public void setPremiumSubsidized(BigDecimal premiumSubsidized) {
    this.premiumSubsidized = premiumSubsidized;
  }

  public ACAPlan2018 premium(BigDecimal premium) {
    this.premium = premium;
    return this;
  }

   /**
   * Cumulative premium amount
   * @return premium
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount")
  public BigDecimal getPremium() {
    return premium;
  }

  public void setPremium(BigDecimal premium) {
    this.premium = premium;
  }

  public ACAPlan2018 premiumSource(String premiumSource) {
    this.premiumSource = premiumSource;
    return this;
  }

   /**
   * Source of the base pricing data
   * @return premiumSource
  **/
  @ApiModelProperty(example = "null", value = "Source of the base pricing data")
  public String getPremiumSource() {
    return premiumSource;
  }

  public void setPremiumSource(String premiumSource) {
    this.premiumSource = premiumSource;
  }

  public ACAPlan2018 primaryCarePhysician(String primaryCarePhysician) {
    this.primaryCarePhysician = primaryCarePhysician;
    return this;
  }

   /**
   * Cost under the plan to visit a Primary Care Physician
   * @return primaryCarePhysician
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan to visit a Primary Care Physician")
  public String getPrimaryCarePhysician() {
    return primaryCarePhysician;
  }

  public void setPrimaryCarePhysician(String primaryCarePhysician) {
    this.primaryCarePhysician = primaryCarePhysician;
  }

  public ACAPlan2018 rehabilitationServices(String rehabilitationServices) {
    this.rehabilitationServices = rehabilitationServices;
    return this;
  }

   /**
   * Benefits summary for rehabilitation services
   * @return rehabilitationServices
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for rehabilitation services")
  public String getRehabilitationServices() {
    return rehabilitationServices;
  }

  public void setRehabilitationServices(String rehabilitationServices) {
    this.rehabilitationServices = rehabilitationServices;
  }

  public ACAPlan2018 skilledNursing(String skilledNursing) {
    this.skilledNursing = skilledNursing;
    return this;
  }

   /**
   * Benefits summary for skilled nursing services
   * @return skilledNursing
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for skilled nursing services")
  public String getSkilledNursing() {
    return skilledNursing;
  }

  public void setSkilledNursing(String skilledNursing) {
    this.skilledNursing = skilledNursing;
  }

  public ACAPlan2018 specialist(String specialist) {
    this.specialist = specialist;
    return this;
  }

   /**
   * Cost under the plan to visit a specialist
   * @return specialist
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan to visit a specialist")
  public String getSpecialist() {
    return specialist;
  }

  public void setSpecialist(String specialist) {
    this.specialist = specialist;
  }

  public ACAPlan2018 specialtyDrugs(String specialtyDrugs) {
    this.specialtyDrugs = specialtyDrugs;
    return this;
  }

   /**
   * Cost under the plan for specialty drugs
   * @return specialtyDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for specialty drugs")
  public String getSpecialtyDrugs() {
    return specialtyDrugs;
  }

  public void setSpecialtyDrugs(String specialtyDrugs) {
    this.specialtyDrugs = specialtyDrugs;
  }

  public ACAPlan2018 urgentCare(String urgentCare) {
    this.urgentCare = urgentCare;
    return this;
  }

   /**
   * Benefits summary for urgent care
   * @return urgentCare
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for urgent care")
  public String getUrgentCare() {
    return urgentCare;
  }

  public void setUrgentCare(String urgentCare) {
    this.urgentCare = urgentCare;
  }

  public ACAPlan2018 actuarialValue(BigDecimal actuarialValue) {
    this.actuarialValue = actuarialValue;
    return this;
  }

   /**
   * Percentage of total average costs for covered benefits that a plan will cover.
   * @return actuarialValue
  **/
  @ApiModelProperty(example = "null", value = "Percentage of total average costs for covered benefits that a plan will cover.")
  public BigDecimal getActuarialValue() {
    return actuarialValue;
  }

  public void setActuarialValue(BigDecimal actuarialValue) {
    this.actuarialValue = actuarialValue;
  }

  public ACAPlan2018 chiropracticServices(String chiropracticServices) {
    this.chiropracticServices = chiropracticServices;
    return this;
  }

   /**
   * Chiropractic services benefits summary
   * @return chiropracticServices
  **/
  @ApiModelProperty(example = "null", value = "Chiropractic services benefits summary")
  public String getChiropracticServices() {
    return chiropracticServices;
  }

  public void setChiropracticServices(String chiropracticServices) {
    this.chiropracticServices = chiropracticServices;
  }

  public ACAPlan2018 coinsurance(BigDecimal coinsurance) {
    this.coinsurance = coinsurance;
    return this;
  }

   /**
   * Standard cost share for most benefits
   * @return coinsurance
  **/
  @ApiModelProperty(example = "null", value = "Standard cost share for most benefits")
  public BigDecimal getCoinsurance() {
    return coinsurance;
  }

  public void setCoinsurance(BigDecimal coinsurance) {
    this.coinsurance = coinsurance;
  }

  public ACAPlan2018 embeddedDeductible(String embeddedDeductible) {
    this.embeddedDeductible = embeddedDeductible;
    return this;
  }

   /**
   * Is the individual deductible for each covered person, embedded in the family deductible
   * @return embeddedDeductible
  **/
  @ApiModelProperty(example = "null", value = "Is the individual deductible for each covered person, embedded in the family deductible")
  public String getEmbeddedDeductible() {
    return embeddedDeductible;
  }

  public void setEmbeddedDeductible(String embeddedDeductible) {
    this.embeddedDeductible = embeddedDeductible;
  }

  public ACAPlan2018 gated(Boolean gated) {
    this.gated = gated;
    return this;
  }

   /**
   * Does the plan's network require a physician referral?
   * @return gated
  **/
  @ApiModelProperty(example = "null", value = "Does the plan's network require a physician referral?")
  public Boolean getGated() {
    return gated;
  }

  public void setGated(Boolean gated) {
    this.gated = gated;
  }

  public ACAPlan2018 imagingCenter(String imagingCenter) {
    this.imagingCenter = imagingCenter;
    return this;
  }

   /**
   * Imaging center benefits summary
   * @return imagingCenter
  **/
  @ApiModelProperty(example = "null", value = "Imaging center benefits summary")
  public String getImagingCenter() {
    return imagingCenter;
  }

  public void setImagingCenter(String imagingCenter) {
    this.imagingCenter = imagingCenter;
  }

  public ACAPlan2018 imagingPhysician(String imagingPhysician) {
    this.imagingPhysician = imagingPhysician;
    return this;
  }

   /**
   * Imaging physician benefits summary
   * @return imagingPhysician
  **/
  @ApiModelProperty(example = "null", value = "Imaging physician benefits summary")
  public String getImagingPhysician() {
    return imagingPhysician;
  }

  public void setImagingPhysician(String imagingPhysician) {
    this.imagingPhysician = imagingPhysician;
  }

  public ACAPlan2018 labTest(String labTest) {
    this.labTest = labTest;
    return this;
  }

   /**
   * Lab test benefits summary
   * @return labTest
  **/
  @ApiModelProperty(example = "null", value = "Lab test benefits summary")
  public String getLabTest() {
    return labTest;
  }

  public void setLabTest(String labTest) {
    this.labTest = labTest;
  }

  public ACAPlan2018 mailOrderRx(BigDecimal mailOrderRx) {
    this.mailOrderRx = mailOrderRx;
    return this;
  }

   /**
   * Multiple of the standard Rx cost share for orders filled via mail order
   * @return mailOrderRx
  **/
  @ApiModelProperty(example = "null", value = "Multiple of the standard Rx cost share for orders filled via mail order")
  public BigDecimal getMailOrderRx() {
    return mailOrderRx;
  }

  public void setMailOrderRx(BigDecimal mailOrderRx) {
    this.mailOrderRx = mailOrderRx;
  }

  public ACAPlan2018 nonpreferredGenericDrugShare(String nonpreferredGenericDrugShare) {
    this.nonpreferredGenericDrugShare = nonpreferredGenericDrugShare;
    return this;
  }

   /**
   * Non-preferred generic drugs benefits summary
   * @return nonpreferredGenericDrugShare
  **/
  @ApiModelProperty(example = "null", value = "Non-preferred generic drugs benefits summary")
  public String getNonpreferredGenericDrugShare() {
    return nonpreferredGenericDrugShare;
  }

  public void setNonpreferredGenericDrugShare(String nonpreferredGenericDrugShare) {
    this.nonpreferredGenericDrugShare = nonpreferredGenericDrugShare;
  }

  public ACAPlan2018 nonpreferredSpecialtyDrugShare(String nonpreferredSpecialtyDrugShare) {
    this.nonpreferredSpecialtyDrugShare = nonpreferredSpecialtyDrugShare;
    return this;
  }

   /**
   * Non-preferred specialty drugs benefits summary
   * @return nonpreferredSpecialtyDrugShare
  **/
  @ApiModelProperty(example = "null", value = "Non-preferred specialty drugs benefits summary")
  public String getNonpreferredSpecialtyDrugShare() {
    return nonpreferredSpecialtyDrugShare;
  }

  public void setNonpreferredSpecialtyDrugShare(String nonpreferredSpecialtyDrugShare) {
    this.nonpreferredSpecialtyDrugShare = nonpreferredSpecialtyDrugShare;
  }

  public ACAPlan2018 outpatientAmbulatoryCareCenter(String outpatientAmbulatoryCareCenter) {
    this.outpatientAmbulatoryCareCenter = outpatientAmbulatoryCareCenter;
    return this;
  }

   /**
   * Outpatient ambulatory care center benefits summary
   * @return outpatientAmbulatoryCareCenter
  **/
  @ApiModelProperty(example = "null", value = "Outpatient ambulatory care center benefits summary")
  public String getOutpatientAmbulatoryCareCenter() {
    return outpatientAmbulatoryCareCenter;
  }

  public void setOutpatientAmbulatoryCareCenter(String outpatientAmbulatoryCareCenter) {
    this.outpatientAmbulatoryCareCenter = outpatientAmbulatoryCareCenter;
  }

  public ACAPlan2018 planCalendar(String planCalendar) {
    this.planCalendar = planCalendar;
    return this;
  }

   /**
   * Are deductibles and MOOPs reset on Dec-31 (\"calendar year\") or 365 days after enrollment date (\"plan year\")?
   * @return planCalendar
  **/
  @ApiModelProperty(example = "null", value = "Are deductibles and MOOPs reset on Dec-31 (\"calendar year\") or 365 days after enrollment date (\"plan year\")?")
  public String getPlanCalendar() {
    return planCalendar;
  }

  public void setPlanCalendar(String planCalendar) {
    this.planCalendar = planCalendar;
  }

  public ACAPlan2018 prenatalCare(String prenatalCare) {
    this.prenatalCare = prenatalCare;
    return this;
  }

   /**
   * Prenatal care benefits summary
   * @return prenatalCare
  **/
  @ApiModelProperty(example = "null", value = "Prenatal care benefits summary")
  public String getPrenatalCare() {
    return prenatalCare;
  }

  public void setPrenatalCare(String prenatalCare) {
    this.prenatalCare = prenatalCare;
  }

  public ACAPlan2018 postnatalCare(String postnatalCare) {
    this.postnatalCare = postnatalCare;
    return this;
  }

   /**
   * Post-natal care benefits summary
   * @return postnatalCare
  **/
  @ApiModelProperty(example = "null", value = "Post-natal care benefits summary")
  public String getPostnatalCare() {
    return postnatalCare;
  }

  public void setPostnatalCare(String postnatalCare) {
    this.postnatalCare = postnatalCare;
  }

  public ACAPlan2018 skilledNursingFacility365(String skilledNursingFacility365) {
    this.skilledNursingFacility365 = skilledNursingFacility365;
    return this;
  }

   /**
   * Does the plan cover full-time, year-round, nursing facilities?
   * @return skilledNursingFacility365
  **/
  @ApiModelProperty(example = "null", value = "Does the plan cover full-time, year-round, nursing facilities?")
  public String getSkilledNursingFacility365() {
    return skilledNursingFacility365;
  }

  public void setSkilledNursingFacility365(String skilledNursingFacility365) {
    this.skilledNursingFacility365 = skilledNursingFacility365;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ACAPlan2018 aCAPlan2018 = (ACAPlan2018) o;
    return Objects.equals(this.carrierName, aCAPlan2018.carrierName) &&
        Objects.equals(this.displayName, aCAPlan2018.displayName) &&
        Objects.equals(this.effectiveDate, aCAPlan2018.effectiveDate) &&
        Objects.equals(this.expirationDate, aCAPlan2018.expirationDate) &&
        Objects.equals(this.identifiers, aCAPlan2018.identifiers) &&
        Objects.equals(this.name, aCAPlan2018.name) &&
        Objects.equals(this.networkIds, aCAPlan2018.networkIds) &&
        Objects.equals(this.networkSize, aCAPlan2018.networkSize) &&
        Objects.equals(this.planType, aCAPlan2018.planType) &&
        Objects.equals(this.serviceAreaId, aCAPlan2018.serviceAreaId) &&
        Objects.equals(this.source, aCAPlan2018.source) &&
        Objects.equals(this.type, aCAPlan2018.type) &&
        Objects.equals(this.adultDental, aCAPlan2018.adultDental) &&
        Objects.equals(this.age29Rider, aCAPlan2018.age29Rider) &&
        Objects.equals(this.ambulance, aCAPlan2018.ambulance) &&
        Objects.equals(this.benefitsSummaryUrl, aCAPlan2018.benefitsSummaryUrl) &&
        Objects.equals(this.buyLink, aCAPlan2018.buyLink) &&
        Objects.equals(this.childDental, aCAPlan2018.childDental) &&
        Objects.equals(this.childEyewear, aCAPlan2018.childEyewear) &&
        Objects.equals(this.childEyeExam, aCAPlan2018.childEyeExam) &&
        Objects.equals(this.customerServicePhoneNumber, aCAPlan2018.customerServicePhoneNumber) &&
        Objects.equals(this.durableMedicalEquipment, aCAPlan2018.durableMedicalEquipment) &&
        Objects.equals(this.diagnosticTest, aCAPlan2018.diagnosticTest) &&
        Objects.equals(this.dpRider, aCAPlan2018.dpRider) &&
        Objects.equals(this.drugFormularyUrl, aCAPlan2018.drugFormularyUrl) &&
        Objects.equals(this.emergencyRoom, aCAPlan2018.emergencyRoom) &&
        Objects.equals(this.familyDrugDeductible, aCAPlan2018.familyDrugDeductible) &&
        Objects.equals(this.familyDrugMoop, aCAPlan2018.familyDrugMoop) &&
        Objects.equals(this.familyMedicalDeductible, aCAPlan2018.familyMedicalDeductible) &&
        Objects.equals(this.familyMedicalMoop, aCAPlan2018.familyMedicalMoop) &&
        Objects.equals(this.fpRider, aCAPlan2018.fpRider) &&
        Objects.equals(this.genericDrugs, aCAPlan2018.genericDrugs) &&
        Objects.equals(this.habilitationServices, aCAPlan2018.habilitationServices) &&
        Objects.equals(this.hiosIssuerId, aCAPlan2018.hiosIssuerId) &&
        Objects.equals(this.homeHealthCare, aCAPlan2018.homeHealthCare) &&
        Objects.equals(this.hospiceService, aCAPlan2018.hospiceService) &&
        Objects.equals(this.hsaEligible, aCAPlan2018.hsaEligible) &&
        Objects.equals(this.id, aCAPlan2018.id) &&
        Objects.equals(this.imaging, aCAPlan2018.imaging) &&
        Objects.equals(this.individualDrugDeductible, aCAPlan2018.individualDrugDeductible) &&
        Objects.equals(this.individualDrugMoop, aCAPlan2018.individualDrugMoop) &&
        Objects.equals(this.individualMedicalDeductible, aCAPlan2018.individualMedicalDeductible) &&
        Objects.equals(this.individualMedicalMoop, aCAPlan2018.individualMedicalMoop) &&
        Objects.equals(this.inpatientBirth, aCAPlan2018.inpatientBirth) &&
        Objects.equals(this.inpatientFacility, aCAPlan2018.inpatientFacility) &&
        Objects.equals(this.inpatientMentalHealth, aCAPlan2018.inpatientMentalHealth) &&
        Objects.equals(this.inpatientPhysician, aCAPlan2018.inpatientPhysician) &&
        Objects.equals(this.inpatientSubstance, aCAPlan2018.inpatientSubstance) &&
        Objects.equals(this.inNetworkIds, aCAPlan2018.inNetworkIds) &&
        Objects.equals(this.level, aCAPlan2018.level) &&
        Objects.equals(this.logoUrl, aCAPlan2018.logoUrl) &&
        Objects.equals(this.nonPreferredBrandDrugs, aCAPlan2018.nonPreferredBrandDrugs) &&
        Objects.equals(this.onMarket, aCAPlan2018.onMarket) &&
        Objects.equals(this.offMarket, aCAPlan2018.offMarket) &&
        Objects.equals(this.outOfNetworkCoverage, aCAPlan2018.outOfNetworkCoverage) &&
        Objects.equals(this.outOfNetworkIds, aCAPlan2018.outOfNetworkIds) &&
        Objects.equals(this.outpatientFacility, aCAPlan2018.outpatientFacility) &&
        Objects.equals(this.outpatientMentalHealth, aCAPlan2018.outpatientMentalHealth) &&
        Objects.equals(this.outpatientPhysician, aCAPlan2018.outpatientPhysician) &&
        Objects.equals(this.outpatientSubstance, aCAPlan2018.outpatientSubstance) &&
        Objects.equals(this.planMarket, aCAPlan2018.planMarket) &&
        Objects.equals(this.preferredBrandDrugs, aCAPlan2018.preferredBrandDrugs) &&
        Objects.equals(this.prenatalPostnatalCare, aCAPlan2018.prenatalPostnatalCare) &&
        Objects.equals(this.preventativeCare, aCAPlan2018.preventativeCare) &&
        Objects.equals(this.premiumSubsidized, aCAPlan2018.premiumSubsidized) &&
        Objects.equals(this.premium, aCAPlan2018.premium) &&
        Objects.equals(this.premiumSource, aCAPlan2018.premiumSource) &&
        Objects.equals(this.primaryCarePhysician, aCAPlan2018.primaryCarePhysician) &&
        Objects.equals(this.rehabilitationServices, aCAPlan2018.rehabilitationServices) &&
        Objects.equals(this.skilledNursing, aCAPlan2018.skilledNursing) &&
        Objects.equals(this.specialist, aCAPlan2018.specialist) &&
        Objects.equals(this.specialtyDrugs, aCAPlan2018.specialtyDrugs) &&
        Objects.equals(this.urgentCare, aCAPlan2018.urgentCare) &&
        Objects.equals(this.actuarialValue, aCAPlan2018.actuarialValue) &&
        Objects.equals(this.chiropracticServices, aCAPlan2018.chiropracticServices) &&
        Objects.equals(this.coinsurance, aCAPlan2018.coinsurance) &&
        Objects.equals(this.embeddedDeductible, aCAPlan2018.embeddedDeductible) &&
        Objects.equals(this.gated, aCAPlan2018.gated) &&
        Objects.equals(this.imagingCenter, aCAPlan2018.imagingCenter) &&
        Objects.equals(this.imagingPhysician, aCAPlan2018.imagingPhysician) &&
        Objects.equals(this.labTest, aCAPlan2018.labTest) &&
        Objects.equals(this.mailOrderRx, aCAPlan2018.mailOrderRx) &&
        Objects.equals(this.nonpreferredGenericDrugShare, aCAPlan2018.nonpreferredGenericDrugShare) &&
        Objects.equals(this.nonpreferredSpecialtyDrugShare, aCAPlan2018.nonpreferredSpecialtyDrugShare) &&
        Objects.equals(this.outpatientAmbulatoryCareCenter, aCAPlan2018.outpatientAmbulatoryCareCenter) &&
        Objects.equals(this.planCalendar, aCAPlan2018.planCalendar) &&
        Objects.equals(this.prenatalCare, aCAPlan2018.prenatalCare) &&
        Objects.equals(this.postnatalCare, aCAPlan2018.postnatalCare) &&
        Objects.equals(this.skilledNursingFacility365, aCAPlan2018.skilledNursingFacility365);
  }

  @Override
  public int hashCode() {
    return Objects.hash(carrierName, displayName, effectiveDate, expirationDate, identifiers, name, networkIds, networkSize, planType, serviceAreaId, source, type, adultDental, age29Rider, ambulance, benefitsSummaryUrl, buyLink, childDental, childEyewear, childEyeExam, customerServicePhoneNumber, durableMedicalEquipment, diagnosticTest, dpRider, drugFormularyUrl, emergencyRoom, familyDrugDeductible, familyDrugMoop, familyMedicalDeductible, familyMedicalMoop, fpRider, genericDrugs, habilitationServices, hiosIssuerId, homeHealthCare, hospiceService, hsaEligible, id, imaging, individualDrugDeductible, individualDrugMoop, individualMedicalDeductible, individualMedicalMoop, inpatientBirth, inpatientFacility, inpatientMentalHealth, inpatientPhysician, inpatientSubstance, inNetworkIds, level, logoUrl, nonPreferredBrandDrugs, onMarket, offMarket, outOfNetworkCoverage, outOfNetworkIds, outpatientFacility, outpatientMentalHealth, outpatientPhysician, outpatientSubstance, planMarket, preferredBrandDrugs, prenatalPostnatalCare, preventativeCare, premiumSubsidized, premium, premiumSource, primaryCarePhysician, rehabilitationServices, skilledNursing, specialist, specialtyDrugs, urgentCare, actuarialValue, chiropracticServices, coinsurance, embeddedDeductible, gated, imagingCenter, imagingPhysician, labTest, mailOrderRx, nonpreferredGenericDrugShare, nonpreferredSpecialtyDrugShare, outpatientAmbulatoryCareCenter, planCalendar, prenatalCare, postnatalCare, skilledNursingFacility365);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ACAPlan2018 {\n");
    
    sb.append("    carrierName: ").append(toIndentedString(carrierName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networkIds: ").append(toIndentedString(networkIds)).append("\n");
    sb.append("    networkSize: ").append(toIndentedString(networkSize)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    serviceAreaId: ").append(toIndentedString(serviceAreaId)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    adultDental: ").append(toIndentedString(adultDental)).append("\n");
    sb.append("    age29Rider: ").append(toIndentedString(age29Rider)).append("\n");
    sb.append("    ambulance: ").append(toIndentedString(ambulance)).append("\n");
    sb.append("    benefitsSummaryUrl: ").append(toIndentedString(benefitsSummaryUrl)).append("\n");
    sb.append("    buyLink: ").append(toIndentedString(buyLink)).append("\n");
    sb.append("    childDental: ").append(toIndentedString(childDental)).append("\n");
    sb.append("    childEyewear: ").append(toIndentedString(childEyewear)).append("\n");
    sb.append("    childEyeExam: ").append(toIndentedString(childEyeExam)).append("\n");
    sb.append("    customerServicePhoneNumber: ").append(toIndentedString(customerServicePhoneNumber)).append("\n");
    sb.append("    durableMedicalEquipment: ").append(toIndentedString(durableMedicalEquipment)).append("\n");
    sb.append("    diagnosticTest: ").append(toIndentedString(diagnosticTest)).append("\n");
    sb.append("    dpRider: ").append(toIndentedString(dpRider)).append("\n");
    sb.append("    drugFormularyUrl: ").append(toIndentedString(drugFormularyUrl)).append("\n");
    sb.append("    emergencyRoom: ").append(toIndentedString(emergencyRoom)).append("\n");
    sb.append("    familyDrugDeductible: ").append(toIndentedString(familyDrugDeductible)).append("\n");
    sb.append("    familyDrugMoop: ").append(toIndentedString(familyDrugMoop)).append("\n");
    sb.append("    familyMedicalDeductible: ").append(toIndentedString(familyMedicalDeductible)).append("\n");
    sb.append("    familyMedicalMoop: ").append(toIndentedString(familyMedicalMoop)).append("\n");
    sb.append("    fpRider: ").append(toIndentedString(fpRider)).append("\n");
    sb.append("    genericDrugs: ").append(toIndentedString(genericDrugs)).append("\n");
    sb.append("    habilitationServices: ").append(toIndentedString(habilitationServices)).append("\n");
    sb.append("    hiosIssuerId: ").append(toIndentedString(hiosIssuerId)).append("\n");
    sb.append("    homeHealthCare: ").append(toIndentedString(homeHealthCare)).append("\n");
    sb.append("    hospiceService: ").append(toIndentedString(hospiceService)).append("\n");
    sb.append("    hsaEligible: ").append(toIndentedString(hsaEligible)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imaging: ").append(toIndentedString(imaging)).append("\n");
    sb.append("    individualDrugDeductible: ").append(toIndentedString(individualDrugDeductible)).append("\n");
    sb.append("    individualDrugMoop: ").append(toIndentedString(individualDrugMoop)).append("\n");
    sb.append("    individualMedicalDeductible: ").append(toIndentedString(individualMedicalDeductible)).append("\n");
    sb.append("    individualMedicalMoop: ").append(toIndentedString(individualMedicalMoop)).append("\n");
    sb.append("    inpatientBirth: ").append(toIndentedString(inpatientBirth)).append("\n");
    sb.append("    inpatientFacility: ").append(toIndentedString(inpatientFacility)).append("\n");
    sb.append("    inpatientMentalHealth: ").append(toIndentedString(inpatientMentalHealth)).append("\n");
    sb.append("    inpatientPhysician: ").append(toIndentedString(inpatientPhysician)).append("\n");
    sb.append("    inpatientSubstance: ").append(toIndentedString(inpatientSubstance)).append("\n");
    sb.append("    inNetworkIds: ").append(toIndentedString(inNetworkIds)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    nonPreferredBrandDrugs: ").append(toIndentedString(nonPreferredBrandDrugs)).append("\n");
    sb.append("    onMarket: ").append(toIndentedString(onMarket)).append("\n");
    sb.append("    offMarket: ").append(toIndentedString(offMarket)).append("\n");
    sb.append("    outOfNetworkCoverage: ").append(toIndentedString(outOfNetworkCoverage)).append("\n");
    sb.append("    outOfNetworkIds: ").append(toIndentedString(outOfNetworkIds)).append("\n");
    sb.append("    outpatientFacility: ").append(toIndentedString(outpatientFacility)).append("\n");
    sb.append("    outpatientMentalHealth: ").append(toIndentedString(outpatientMentalHealth)).append("\n");
    sb.append("    outpatientPhysician: ").append(toIndentedString(outpatientPhysician)).append("\n");
    sb.append("    outpatientSubstance: ").append(toIndentedString(outpatientSubstance)).append("\n");
    sb.append("    planMarket: ").append(toIndentedString(planMarket)).append("\n");
    sb.append("    preferredBrandDrugs: ").append(toIndentedString(preferredBrandDrugs)).append("\n");
    sb.append("    prenatalPostnatalCare: ").append(toIndentedString(prenatalPostnatalCare)).append("\n");
    sb.append("    preventativeCare: ").append(toIndentedString(preventativeCare)).append("\n");
    sb.append("    premiumSubsidized: ").append(toIndentedString(premiumSubsidized)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    premiumSource: ").append(toIndentedString(premiumSource)).append("\n");
    sb.append("    primaryCarePhysician: ").append(toIndentedString(primaryCarePhysician)).append("\n");
    sb.append("    rehabilitationServices: ").append(toIndentedString(rehabilitationServices)).append("\n");
    sb.append("    skilledNursing: ").append(toIndentedString(skilledNursing)).append("\n");
    sb.append("    specialist: ").append(toIndentedString(specialist)).append("\n");
    sb.append("    specialtyDrugs: ").append(toIndentedString(specialtyDrugs)).append("\n");
    sb.append("    urgentCare: ").append(toIndentedString(urgentCare)).append("\n");
    sb.append("    actuarialValue: ").append(toIndentedString(actuarialValue)).append("\n");
    sb.append("    chiropracticServices: ").append(toIndentedString(chiropracticServices)).append("\n");
    sb.append("    coinsurance: ").append(toIndentedString(coinsurance)).append("\n");
    sb.append("    embeddedDeductible: ").append(toIndentedString(embeddedDeductible)).append("\n");
    sb.append("    gated: ").append(toIndentedString(gated)).append("\n");
    sb.append("    imagingCenter: ").append(toIndentedString(imagingCenter)).append("\n");
    sb.append("    imagingPhysician: ").append(toIndentedString(imagingPhysician)).append("\n");
    sb.append("    labTest: ").append(toIndentedString(labTest)).append("\n");
    sb.append("    mailOrderRx: ").append(toIndentedString(mailOrderRx)).append("\n");
    sb.append("    nonpreferredGenericDrugShare: ").append(toIndentedString(nonpreferredGenericDrugShare)).append("\n");
    sb.append("    nonpreferredSpecialtyDrugShare: ").append(toIndentedString(nonpreferredSpecialtyDrugShare)).append("\n");
    sb.append("    outpatientAmbulatoryCareCenter: ").append(toIndentedString(outpatientAmbulatoryCareCenter)).append("\n");
    sb.append("    planCalendar: ").append(toIndentedString(planCalendar)).append("\n");
    sb.append("    prenatalCare: ").append(toIndentedString(prenatalCare)).append("\n");
    sb.append("    postnatalCare: ").append(toIndentedString(postnatalCare)).append("\n");
    sb.append("    skilledNursingFacility365: ").append(toIndentedString(skilledNursingFacility365)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

