/*
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,states.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
root                      ::= coverage

coverage                  ::= (simple_coverage | tiered_coverage) (space pipe space coverage_modifier)?
tiered_coverage           ::= tier (space slash space tier)*
tier                      ::= tier_name colon space (tier_coverage | not_applicable)
tier_coverage             ::= simple_coverage (space (then | or | and) space simple_coverage)* tier_limitation?
simple_coverage           ::= (pre_coverage_limitation space)? coverage_amount (space post_coverage_limitation)? (comma? space coverage_condition)?
coverage_modifier         ::= limit_condition colon space (((simple_coverage | simple_limitation) (semicolon space see_carrier_documentation)?) | see_carrier_documentation | waived_if_admitted | shared_across_tiers)
waived_if_admitted        ::= ("copay" space)? "waived if admitted"
simple_limitation         ::= pre_coverage_limitation space "copay applies"
tier_name                 ::= "In-Network-Tier-2" | "Out-of-Network" | "In-Network"
limit_condition           ::= "limit" | "condition"
tier_limitation           ::= comma space "up to" space (currency | (integer space time_unit plural?)) (space post_coverage_limitation)?
coverage_amount           ::= currency | unlimited | included | unknown | percentage | (digits space (treatment_unit | time_unit) plural?)
pre_coverage_limitation   ::= first space digits space time_unit plural?
post_coverage_limitation  ::= (((then space currency) | "per condition") space)? "per" space (treatment_unit | (integer space time_unit) | time_unit) plural?
coverage_condition        ::= ("before deductible" | "after deductible" | "penalty" | allowance | "in-state" | "out-of-state") (space allowance)?
allowance                 ::= upto_allowance | after_allowance
upto_allowance            ::= "up to" space (currency space)? "allowance"
after_allowance           ::= "after" space (currency space)? "allowance"
see_carrier_documentation ::= "see carrier documentation for more information"
shared_across_tiers       ::= "shared across all tiers"
unknown                   ::= "unknown"
unlimited                 ::= /[uU]nlimited/
included                  ::= /[iI]ncluded in [mM]edical/
time_unit                 ::= /[hH]our/ | (((/[cC]alendar/ | /[cC]ontract/) space)? /[yY]ear/) | /[mM]onth/ | /[dD]ay/ | /[wW]eek/ | /[vV]isit/ | /[lL]ifetime/ | ((((/[bB]enefit/ plural?) | /[eE]ligibility/) space)? /[pP]eriod/)
treatment_unit            ::= /[pP]erson/ | /[gG]roup/ | /[cC]ondition/ | /[sS]cript/ | /[vV]isit/ | /[eE]xam/ | /[iI]tem/ | /[sS]tay/ | /[tT]reatment/ | /[aA]dmission/ | /[eE]pisode/
comma                     ::= ","
colon                     ::= ":"
semicolon                 ::= ";"
pipe                      ::= "|"
slash                     ::= "/"
plural                    ::= "(s)" | "s"
then                      ::= "then" | ("," space) | space
or                        ::= "or"
and                       ::= "and"
not_applicable            ::= "Not Applicable" | "N/A" | "NA"
first                     ::= "first"
currency                  ::= "$" number
percentage                ::= number "%"
number                    ::= float | integer
float                     ::= digits "." digits
integer                   ::= /[0-9]/+ (comma_int | under_int)*
comma_int                 ::= ("," /[0-9]/*3) !"_"
under_int                 ::= ("_" /[0-9]/*3) !","
digits                    ::= /[0-9]/+ ("_" /[0-9]/+)*
space                     ::= /[ \t]/+
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * DentalPlanBenefits
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T16:41:18.837-04:00")
public class DentalPlanBenefits  implements Serializable {
  @JsonProperty("individual_deductible")
  private String individualDeductible = null;

  @JsonProperty("family_deductible")
  private String familyDeductible = null;

  @JsonProperty("individual_annual_max")
  private String individualAnnualMax = null;

  @JsonProperty("family_max_annual_max")
  private String familyMaxAnnualMax = null;

  @JsonProperty("individual_moop")
  private String individualMoop = null;

  @JsonProperty("family_moop")
  private String familyMoop = null;

  @JsonProperty("office_visits")
  private String officeVisits = null;

  @JsonProperty("radiograph_bitewings")
  private String radiographBitewings = null;

  @JsonProperty("radiograph_other")
  private String radiographOther = null;

  @JsonProperty("fluoride_treatment")
  private String fluorideTreatment = null;

  @JsonProperty("space_maintainers")
  private String spaceMaintainers = null;

  @JsonProperty("prophylaxis_cleaning")
  private String prophylaxisCleaning = null;

  @JsonProperty("sealant")
  private String sealant = null;

  @JsonProperty("fillings_amalgram")
  private String fillingsAmalgram = null;

  @JsonProperty("fillings_composite")
  private String fillingsComposite = null;

  @JsonProperty("emergency_treatment")
  private String emergencyTreatment = null;

  @JsonProperty("restorative")
  private String restorative = null;

  @JsonProperty("surgery_anesthesia")
  private String surgeryAnesthesia = null;

  @JsonProperty("surgery_extraction")
  private String surgeryExtraction = null;

  @JsonProperty("endodontics")
  private String endodontics = null;

  @JsonProperty("periodontics")
  private String periodontics = null;

  @JsonProperty("orthodontics_adult")
  private String orthodonticsAdult = null;

  @JsonProperty("orthodontics_child")
  private String orthodonticsChild = null;

  public DentalPlanBenefits individualDeductible(String individualDeductible) {
    this.individualDeductible = individualDeductible;
    return this;
  }

   /**
   * Individual Deductible benefit string
   * @return individualDeductible
  **/
  @ApiModelProperty(example = "null", value = "Individual Deductible benefit string")
  public String getIndividualDeductible() {
    return individualDeductible;
  }

  public void setIndividualDeductible(String individualDeductible) {
    this.individualDeductible = individualDeductible;
  }

  public DentalPlanBenefits familyDeductible(String familyDeductible) {
    this.familyDeductible = familyDeductible;
    return this;
  }

   /**
   * Family Deductible benefit string
   * @return familyDeductible
  **/
  @ApiModelProperty(example = "null", value = "Family Deductible benefit string")
  public String getFamilyDeductible() {
    return familyDeductible;
  }

  public void setFamilyDeductible(String familyDeductible) {
    this.familyDeductible = familyDeductible;
  }

  public DentalPlanBenefits individualAnnualMax(String individualAnnualMax) {
    this.individualAnnualMax = individualAnnualMax;
    return this;
  }

   /**
   * Individual Annual Max benefit string
   * @return individualAnnualMax
  **/
  @ApiModelProperty(example = "null", value = "Individual Annual Max benefit string")
  public String getIndividualAnnualMax() {
    return individualAnnualMax;
  }

  public void setIndividualAnnualMax(String individualAnnualMax) {
    this.individualAnnualMax = individualAnnualMax;
  }

  public DentalPlanBenefits familyMaxAnnualMax(String familyMaxAnnualMax) {
    this.familyMaxAnnualMax = familyMaxAnnualMax;
    return this;
  }

   /**
   * Family Max Annual Max benefit string
   * @return familyMaxAnnualMax
  **/
  @ApiModelProperty(example = "null", value = "Family Max Annual Max benefit string")
  public String getFamilyMaxAnnualMax() {
    return familyMaxAnnualMax;
  }

  public void setFamilyMaxAnnualMax(String familyMaxAnnualMax) {
    this.familyMaxAnnualMax = familyMaxAnnualMax;
  }

  public DentalPlanBenefits individualMoop(String individualMoop) {
    this.individualMoop = individualMoop;
    return this;
  }

   /**
   * Individual MOOP benefit string
   * @return individualMoop
  **/
  @ApiModelProperty(example = "null", value = "Individual MOOP benefit string")
  public String getIndividualMoop() {
    return individualMoop;
  }

  public void setIndividualMoop(String individualMoop) {
    this.individualMoop = individualMoop;
  }

  public DentalPlanBenefits familyMoop(String familyMoop) {
    this.familyMoop = familyMoop;
    return this;
  }

   /**
   * Family MOOP benefit string
   * @return familyMoop
  **/
  @ApiModelProperty(example = "null", value = "Family MOOP benefit string")
  public String getFamilyMoop() {
    return familyMoop;
  }

  public void setFamilyMoop(String familyMoop) {
    this.familyMoop = familyMoop;
  }

  public DentalPlanBenefits officeVisits(String officeVisits) {
    this.officeVisits = officeVisits;
    return this;
  }

   /**
   * Office Visits benefit string
   * @return officeVisits
  **/
  @ApiModelProperty(example = "null", value = "Office Visits benefit string")
  public String getOfficeVisits() {
    return officeVisits;
  }

  public void setOfficeVisits(String officeVisits) {
    this.officeVisits = officeVisits;
  }

  public DentalPlanBenefits radiographBitewings(String radiographBitewings) {
    this.radiographBitewings = radiographBitewings;
    return this;
  }

   /**
   * Radiograph - Bitewings benefit string
   * @return radiographBitewings
  **/
  @ApiModelProperty(example = "null", value = "Radiograph - Bitewings benefit string")
  public String getRadiographBitewings() {
    return radiographBitewings;
  }

  public void setRadiographBitewings(String radiographBitewings) {
    this.radiographBitewings = radiographBitewings;
  }

  public DentalPlanBenefits radiographOther(String radiographOther) {
    this.radiographOther = radiographOther;
    return this;
  }

   /**
   * Radiograph - Other benefit string
   * @return radiographOther
  **/
  @ApiModelProperty(example = "null", value = "Radiograph - Other benefit string")
  public String getRadiographOther() {
    return radiographOther;
  }

  public void setRadiographOther(String radiographOther) {
    this.radiographOther = radiographOther;
  }

  public DentalPlanBenefits fluorideTreatment(String fluorideTreatment) {
    this.fluorideTreatment = fluorideTreatment;
    return this;
  }

   /**
   * Fluoride Treatment benefit string
   * @return fluorideTreatment
  **/
  @ApiModelProperty(example = "null", value = "Fluoride Treatment benefit string")
  public String getFluorideTreatment() {
    return fluorideTreatment;
  }

  public void setFluorideTreatment(String fluorideTreatment) {
    this.fluorideTreatment = fluorideTreatment;
  }

  public DentalPlanBenefits spaceMaintainers(String spaceMaintainers) {
    this.spaceMaintainers = spaceMaintainers;
    return this;
  }

   /**
   * Space Maintainers benefit string
   * @return spaceMaintainers
  **/
  @ApiModelProperty(example = "null", value = "Space Maintainers benefit string")
  public String getSpaceMaintainers() {
    return spaceMaintainers;
  }

  public void setSpaceMaintainers(String spaceMaintainers) {
    this.spaceMaintainers = spaceMaintainers;
  }

  public DentalPlanBenefits prophylaxisCleaning(String prophylaxisCleaning) {
    this.prophylaxisCleaning = prophylaxisCleaning;
    return this;
  }

   /**
   * Prophylaxis Cleaning benefit string
   * @return prophylaxisCleaning
  **/
  @ApiModelProperty(example = "null", value = "Prophylaxis Cleaning benefit string")
  public String getProphylaxisCleaning() {
    return prophylaxisCleaning;
  }

  public void setProphylaxisCleaning(String prophylaxisCleaning) {
    this.prophylaxisCleaning = prophylaxisCleaning;
  }

  public DentalPlanBenefits sealant(String sealant) {
    this.sealant = sealant;
    return this;
  }

   /**
   * Sealant benefit string
   * @return sealant
  **/
  @ApiModelProperty(example = "null", value = "Sealant benefit string")
  public String getSealant() {
    return sealant;
  }

  public void setSealant(String sealant) {
    this.sealant = sealant;
  }

  public DentalPlanBenefits fillingsAmalgram(String fillingsAmalgram) {
    this.fillingsAmalgram = fillingsAmalgram;
    return this;
  }

   /**
   * Fillings - Amalgram benefit string
   * @return fillingsAmalgram
  **/
  @ApiModelProperty(example = "null", value = "Fillings - Amalgram benefit string")
  public String getFillingsAmalgram() {
    return fillingsAmalgram;
  }

  public void setFillingsAmalgram(String fillingsAmalgram) {
    this.fillingsAmalgram = fillingsAmalgram;
  }

  public DentalPlanBenefits fillingsComposite(String fillingsComposite) {
    this.fillingsComposite = fillingsComposite;
    return this;
  }

   /**
   * Fillings - Composite benefit string
   * @return fillingsComposite
  **/
  @ApiModelProperty(example = "null", value = "Fillings - Composite benefit string")
  public String getFillingsComposite() {
    return fillingsComposite;
  }

  public void setFillingsComposite(String fillingsComposite) {
    this.fillingsComposite = fillingsComposite;
  }

  public DentalPlanBenefits emergencyTreatment(String emergencyTreatment) {
    this.emergencyTreatment = emergencyTreatment;
    return this;
  }

   /**
   * Emergency Treatment benefit string
   * @return emergencyTreatment
  **/
  @ApiModelProperty(example = "null", value = "Emergency Treatment benefit string")
  public String getEmergencyTreatment() {
    return emergencyTreatment;
  }

  public void setEmergencyTreatment(String emergencyTreatment) {
    this.emergencyTreatment = emergencyTreatment;
  }

  public DentalPlanBenefits restorative(String restorative) {
    this.restorative = restorative;
    return this;
  }

   /**
   * Restorative benefit string
   * @return restorative
  **/
  @ApiModelProperty(example = "null", value = "Restorative benefit string")
  public String getRestorative() {
    return restorative;
  }

  public void setRestorative(String restorative) {
    this.restorative = restorative;
  }

  public DentalPlanBenefits surgeryAnesthesia(String surgeryAnesthesia) {
    this.surgeryAnesthesia = surgeryAnesthesia;
    return this;
  }

   /**
   * Surgery - Anesthesia benefit string
   * @return surgeryAnesthesia
  **/
  @ApiModelProperty(example = "null", value = "Surgery - Anesthesia benefit string")
  public String getSurgeryAnesthesia() {
    return surgeryAnesthesia;
  }

  public void setSurgeryAnesthesia(String surgeryAnesthesia) {
    this.surgeryAnesthesia = surgeryAnesthesia;
  }

  public DentalPlanBenefits surgeryExtraction(String surgeryExtraction) {
    this.surgeryExtraction = surgeryExtraction;
    return this;
  }

   /**
   * Surgery - Extraction benefit string
   * @return surgeryExtraction
  **/
  @ApiModelProperty(example = "null", value = "Surgery - Extraction benefit string")
  public String getSurgeryExtraction() {
    return surgeryExtraction;
  }

  public void setSurgeryExtraction(String surgeryExtraction) {
    this.surgeryExtraction = surgeryExtraction;
  }

  public DentalPlanBenefits endodontics(String endodontics) {
    this.endodontics = endodontics;
    return this;
  }

   /**
   * Endodontics benefit string
   * @return endodontics
  **/
  @ApiModelProperty(example = "null", value = "Endodontics benefit string")
  public String getEndodontics() {
    return endodontics;
  }

  public void setEndodontics(String endodontics) {
    this.endodontics = endodontics;
  }

  public DentalPlanBenefits periodontics(String periodontics) {
    this.periodontics = periodontics;
    return this;
  }

   /**
   * Periodontics benefit string
   * @return periodontics
  **/
  @ApiModelProperty(example = "null", value = "Periodontics benefit string")
  public String getPeriodontics() {
    return periodontics;
  }

  public void setPeriodontics(String periodontics) {
    this.periodontics = periodontics;
  }

  public DentalPlanBenefits orthodonticsAdult(String orthodonticsAdult) {
    this.orthodonticsAdult = orthodonticsAdult;
    return this;
  }

   /**
   * Orthodontics - Adult benefit string
   * @return orthodonticsAdult
  **/
  @ApiModelProperty(example = "null", value = "Orthodontics - Adult benefit string")
  public String getOrthodonticsAdult() {
    return orthodonticsAdult;
  }

  public void setOrthodonticsAdult(String orthodonticsAdult) {
    this.orthodonticsAdult = orthodonticsAdult;
  }

  public DentalPlanBenefits orthodonticsChild(String orthodonticsChild) {
    this.orthodonticsChild = orthodonticsChild;
    return this;
  }

   /**
   * Orthodontics - Child benefit string
   * @return orthodonticsChild
  **/
  @ApiModelProperty(example = "null", value = "Orthodontics - Child benefit string")
  public String getOrthodonticsChild() {
    return orthodonticsChild;
  }

  public void setOrthodonticsChild(String orthodonticsChild) {
    this.orthodonticsChild = orthodonticsChild;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DentalPlanBenefits dentalPlanBenefits = (DentalPlanBenefits) o;
    return Objects.equals(this.individualDeductible, dentalPlanBenefits.individualDeductible) &&
        Objects.equals(this.familyDeductible, dentalPlanBenefits.familyDeductible) &&
        Objects.equals(this.individualAnnualMax, dentalPlanBenefits.individualAnnualMax) &&
        Objects.equals(this.familyMaxAnnualMax, dentalPlanBenefits.familyMaxAnnualMax) &&
        Objects.equals(this.individualMoop, dentalPlanBenefits.individualMoop) &&
        Objects.equals(this.familyMoop, dentalPlanBenefits.familyMoop) &&
        Objects.equals(this.officeVisits, dentalPlanBenefits.officeVisits) &&
        Objects.equals(this.radiographBitewings, dentalPlanBenefits.radiographBitewings) &&
        Objects.equals(this.radiographOther, dentalPlanBenefits.radiographOther) &&
        Objects.equals(this.fluorideTreatment, dentalPlanBenefits.fluorideTreatment) &&
        Objects.equals(this.spaceMaintainers, dentalPlanBenefits.spaceMaintainers) &&
        Objects.equals(this.prophylaxisCleaning, dentalPlanBenefits.prophylaxisCleaning) &&
        Objects.equals(this.sealant, dentalPlanBenefits.sealant) &&
        Objects.equals(this.fillingsAmalgram, dentalPlanBenefits.fillingsAmalgram) &&
        Objects.equals(this.fillingsComposite, dentalPlanBenefits.fillingsComposite) &&
        Objects.equals(this.emergencyTreatment, dentalPlanBenefits.emergencyTreatment) &&
        Objects.equals(this.restorative, dentalPlanBenefits.restorative) &&
        Objects.equals(this.surgeryAnesthesia, dentalPlanBenefits.surgeryAnesthesia) &&
        Objects.equals(this.surgeryExtraction, dentalPlanBenefits.surgeryExtraction) &&
        Objects.equals(this.endodontics, dentalPlanBenefits.endodontics) &&
        Objects.equals(this.periodontics, dentalPlanBenefits.periodontics) &&
        Objects.equals(this.orthodonticsAdult, dentalPlanBenefits.orthodonticsAdult) &&
        Objects.equals(this.orthodonticsChild, dentalPlanBenefits.orthodonticsChild);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individualDeductible, familyDeductible, individualAnnualMax, familyMaxAnnualMax, individualMoop, familyMoop, officeVisits, radiographBitewings, radiographOther, fluorideTreatment, spaceMaintainers, prophylaxisCleaning, sealant, fillingsAmalgram, fillingsComposite, emergencyTreatment, restorative, surgeryAnesthesia, surgeryExtraction, endodontics, periodontics, orthodonticsAdult, orthodonticsChild);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DentalPlanBenefits {\n");
    
    sb.append("    individualDeductible: ").append(toIndentedString(individualDeductible)).append("\n");
    sb.append("    familyDeductible: ").append(toIndentedString(familyDeductible)).append("\n");
    sb.append("    individualAnnualMax: ").append(toIndentedString(individualAnnualMax)).append("\n");
    sb.append("    familyMaxAnnualMax: ").append(toIndentedString(familyMaxAnnualMax)).append("\n");
    sb.append("    individualMoop: ").append(toIndentedString(individualMoop)).append("\n");
    sb.append("    familyMoop: ").append(toIndentedString(familyMoop)).append("\n");
    sb.append("    officeVisits: ").append(toIndentedString(officeVisits)).append("\n");
    sb.append("    radiographBitewings: ").append(toIndentedString(radiographBitewings)).append("\n");
    sb.append("    radiographOther: ").append(toIndentedString(radiographOther)).append("\n");
    sb.append("    fluorideTreatment: ").append(toIndentedString(fluorideTreatment)).append("\n");
    sb.append("    spaceMaintainers: ").append(toIndentedString(spaceMaintainers)).append("\n");
    sb.append("    prophylaxisCleaning: ").append(toIndentedString(prophylaxisCleaning)).append("\n");
    sb.append("    sealant: ").append(toIndentedString(sealant)).append("\n");
    sb.append("    fillingsAmalgram: ").append(toIndentedString(fillingsAmalgram)).append("\n");
    sb.append("    fillingsComposite: ").append(toIndentedString(fillingsComposite)).append("\n");
    sb.append("    emergencyTreatment: ").append(toIndentedString(emergencyTreatment)).append("\n");
    sb.append("    restorative: ").append(toIndentedString(restorative)).append("\n");
    sb.append("    surgeryAnesthesia: ").append(toIndentedString(surgeryAnesthesia)).append("\n");
    sb.append("    surgeryExtraction: ").append(toIndentedString(surgeryExtraction)).append("\n");
    sb.append("    endodontics: ").append(toIndentedString(endodontics)).append("\n");
    sb.append("    periodontics: ").append(toIndentedString(periodontics)).append("\n");
    sb.append("    orthodonticsAdult: ").append(toIndentedString(orthodonticsAdult)).append("\n");
    sb.append("    orthodonticsChild: ").append(toIndentedString(orthodonticsChild)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

