/*
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * DrugCoverage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-14T13:33:39.716-04:00")
public class DrugCoverage  implements Serializable {
  @JsonProperty("plan_id")
  private String planId = null;

  @JsonProperty("drug_package_id")
  private String drugPackageId = null;

  @JsonProperty("med_id")
  private Integer medId = null;

  @JsonProperty("quantity_limit")
  private Boolean quantityLimit = null;

  @JsonProperty("prior_authorization")
  private Boolean priorAuthorization = null;

  @JsonProperty("step_therapy")
  private Boolean stepTherapy = null;

  @JsonProperty("tier")
  private String tier = null;

  public DrugCoverage planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Health Insurance Oversight System id
   * @return planId
  **/
  @ApiModelProperty(example = "null", value = "Health Insurance Oversight System id")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public DrugCoverage drugPackageId(String drugPackageId) {
    this.drugPackageId = drugPackageId;
    return this;
  }

   /**
   * NDC package code
   * @return drugPackageId
  **/
  @ApiModelProperty(example = "null", value = "NDC package code")
  public String getDrugPackageId() {
    return drugPackageId;
  }

  public void setDrugPackageId(String drugPackageId) {
    this.drugPackageId = drugPackageId;
  }

  public DrugCoverage medId(Integer medId) {
    this.medId = medId;
    return this;
  }

   /**
   * Med ID
   * @return medId
  **/
  @ApiModelProperty(example = "null", value = "Med ID")
  public Integer getMedId() {
    return medId;
  }

  public void setMedId(Integer medId) {
    this.medId = medId;
  }

  public DrugCoverage quantityLimit(Boolean quantityLimit) {
    this.quantityLimit = quantityLimit;
    return this;
  }

   /**
   * Quantity limit exists
   * @return quantityLimit
  **/
  @ApiModelProperty(example = "null", value = "Quantity limit exists")
  public Boolean getQuantityLimit() {
    return quantityLimit;
  }

  public void setQuantityLimit(Boolean quantityLimit) {
    this.quantityLimit = quantityLimit;
  }

  public DrugCoverage priorAuthorization(Boolean priorAuthorization) {
    this.priorAuthorization = priorAuthorization;
    return this;
  }

   /**
   * Prior authorization required
   * @return priorAuthorization
  **/
  @ApiModelProperty(example = "null", value = "Prior authorization required")
  public Boolean getPriorAuthorization() {
    return priorAuthorization;
  }

  public void setPriorAuthorization(Boolean priorAuthorization) {
    this.priorAuthorization = priorAuthorization;
  }

  public DrugCoverage stepTherapy(Boolean stepTherapy) {
    this.stepTherapy = stepTherapy;
    return this;
  }

   /**
   * Step Treatment required
   * @return stepTherapy
  **/
  @ApiModelProperty(example = "null", value = "Step Treatment required")
  public Boolean getStepTherapy() {
    return stepTherapy;
  }

  public void setStepTherapy(Boolean stepTherapy) {
    this.stepTherapy = stepTherapy;
  }

  public DrugCoverage tier(String tier) {
    this.tier = tier;
    return this;
  }

   /**
   * Tier Name
   * @return tier
  **/
  @ApiModelProperty(example = "null", value = "Tier Name")
  public String getTier() {
    return tier;
  }

  public void setTier(String tier) {
    this.tier = tier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DrugCoverage drugCoverage = (DrugCoverage) o;
    return Objects.equals(this.planId, drugCoverage.planId) &&
        Objects.equals(this.drugPackageId, drugCoverage.drugPackageId) &&
        Objects.equals(this.medId, drugCoverage.medId) &&
        Objects.equals(this.quantityLimit, drugCoverage.quantityLimit) &&
        Objects.equals(this.priorAuthorization, drugCoverage.priorAuthorization) &&
        Objects.equals(this.stepTherapy, drugCoverage.stepTherapy) &&
        Objects.equals(this.tier, drugCoverage.tier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planId, drugPackageId, medId, quantityLimit, priorAuthorization, stepTherapy, tier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DrugCoverage {\n");
    
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    drugPackageId: ").append(toIndentedString(drugPackageId)).append("\n");
    sb.append("    medId: ").append(toIndentedString(medId)).append("\n");
    sb.append("    quantityLimit: ").append(toIndentedString(quantityLimit)).append("\n");
    sb.append("    priorAuthorization: ").append(toIndentedString(priorAuthorization)).append("\n");
    sb.append("    stepTherapy: ").append(toIndentedString(stepTherapy)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

