/**
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import java.io.Serializable;
/**
 * PlanSearchResult
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-24T12:43:20.125-04:00")
public class PlanSearchResult  implements Serializable {
  @JsonProperty("adult_dental")
  private Boolean adultDental = null;

  @JsonProperty("age29_rider")
  private Boolean age29Rider = null;

  @JsonProperty("ambulance")
  private String ambulance = null;

  @JsonProperty("benefits_summary_url")
  private String benefitsSummaryUrl = null;

  @JsonProperty("buy_link")
  private String buyLink = null;

  @JsonProperty("carrier_name")
  private String carrierName = null;

  @JsonProperty("child_dental")
  private Boolean childDental = null;

  @JsonProperty("child_eyewear")
  private String childEyewear = null;

  @JsonProperty("child_eye_exam")
  private String childEyeExam = null;

  @JsonProperty("customer_service_phone_number")
  private String customerServicePhoneNumber = null;

  @JsonProperty("durable_medical_equipment")
  private String durableMedicalEquipment = null;

  @JsonProperty("diagnostic_test")
  private String diagnosticTest = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("dp_rider")
  private Boolean dpRider = null;

  @JsonProperty("drug_formulary_url")
  private String drugFormularyUrl = null;

  @JsonProperty("effective_date")
  private String effectiveDate = null;

  @JsonProperty("expiration_date")
  private String expirationDate = null;

  @JsonProperty("emergency_room")
  private String emergencyRoom = null;

  @JsonProperty("family_drug_deductible")
  private String familyDrugDeductible = null;

  @JsonProperty("family_drug_moop")
  private String familyDrugMoop = null;

  @JsonProperty("family_medical_deductible")
  private String familyMedicalDeductible = null;

  @JsonProperty("family_medical_moop")
  private String familyMedicalMoop = null;

  @JsonProperty("fp_rider")
  private Boolean fpRider = null;

  @JsonProperty("generic_drugs")
  private String genericDrugs = null;

  @JsonProperty("habilitation_services")
  private String habilitationServices = null;

  @JsonProperty("hios_issuer_id")
  private String hiosIssuerId = null;

  @JsonProperty("home_health_care")
  private String homeHealthCare = null;

  @JsonProperty("hospice_service")
  private String hospiceService = null;

  @JsonProperty("hsa_eligible")
  private Boolean hsaEligible = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("imaging")
  private String imaging = null;

  @JsonProperty("in_network_ids")
  private List<Integer> inNetworkIds = new ArrayList<Integer>();

  @JsonProperty("individual_drug_deductible")
  private String individualDrugDeductible = null;

  @JsonProperty("individual_drug_moop")
  private String individualDrugMoop = null;

  @JsonProperty("individual_medical_deductible")
  private String individualMedicalDeductible = null;

  @JsonProperty("individual_medical_moop")
  private String individualMedicalMoop = null;

  @JsonProperty("inpatient_birth")
  private String inpatientBirth = null;

  @JsonProperty("inpatient_facility")
  private String inpatientFacility = null;

  @JsonProperty("inpatient_mental_health")
  private String inpatientMentalHealth = null;

  @JsonProperty("inpatient_physician")
  private String inpatientPhysician = null;

  @JsonProperty("inpatient_substance")
  private String inpatientSubstance = null;

  @JsonProperty("level")
  private String level = null;

  @JsonProperty("logo_url")
  private String logoUrl = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("non_preferred_brand_drugs")
  private String nonPreferredBrandDrugs = null;

  @JsonProperty("on_market")
  private Boolean onMarket = null;

  @JsonProperty("off_market")
  private Boolean offMarket = null;

  @JsonProperty("out_of_network_coverage")
  private Boolean outOfNetworkCoverage = null;

  @JsonProperty("out_of_network_ids")
  private List<Integer> outOfNetworkIds = new ArrayList<Integer>();

  @JsonProperty("outpatient_facility")
  private String outpatientFacility = null;

  @JsonProperty("outpatient_mental_health")
  private String outpatientMentalHealth = null;

  @JsonProperty("outpatient_physician")
  private String outpatientPhysician = null;

  @JsonProperty("outpatient_substance")
  private String outpatientSubstance = null;

  @JsonProperty("plan_market")
  private String planMarket = null;

  @JsonProperty("plan_type")
  private String planType = null;

  @JsonProperty("preferred_brand_drugs")
  private String preferredBrandDrugs = null;

  @JsonProperty("prenatal_postnatal_care")
  private String prenatalPostnatalCare = null;

  @JsonProperty("preventative_care")
  private String preventativeCare = null;

  @JsonProperty("premium_subsidized")
  private BigDecimal premiumSubsidized = null;

  @JsonProperty("premium")
  private BigDecimal premium = null;

  @JsonProperty("primary_care_physician")
  private String primaryCarePhysician = null;

  @JsonProperty("rehabilitation_services")
  private String rehabilitationServices = null;

  @JsonProperty("service_area_id")
  private String serviceAreaId = null;

  @JsonProperty("skilled_nursing")
  private String skilledNursing = null;

  @JsonProperty("specialist")
  private String specialist = null;

  @JsonProperty("specialty_drugs")
  private String specialtyDrugs = null;

  @JsonProperty("urgent_care")
  private String urgentCare = null;

  @JsonProperty("match_percentage")
  private Integer matchPercentage = null;

  @JsonProperty("perfect_match_percentage")
  private Integer perfectMatchPercentage = null;

  @JsonProperty("employee_premium")
  private BigDecimal employeePremium = null;

  @JsonProperty("dependent_premium")
  private BigDecimal dependentPremium = null;

  public PlanSearchResult adultDental(Boolean adultDental) {
    this.adultDental = adultDental;
    return this;
  }

   /**
   * Does the plan provide dental coverage for adults?
   * @return adultDental
  **/
  @ApiModelProperty(example = "null", value = "Does the plan provide dental coverage for adults?")
  public Boolean getAdultDental() {
    return adultDental;
  }

  public void setAdultDental(Boolean adultDental) {
    this.adultDental = adultDental;
  }

  public PlanSearchResult age29Rider(Boolean age29Rider) {
    this.age29Rider = age29Rider;
    return this;
  }

   /**
   * 
   * @return age29Rider
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAge29Rider() {
    return age29Rider;
  }

  public void setAge29Rider(Boolean age29Rider) {
    this.age29Rider = age29Rider;
  }

  public PlanSearchResult ambulance(String ambulance) {
    this.ambulance = ambulance;
    return this;
  }

   /**
   * Benefits string for ambulance coverage
   * @return ambulance
  **/
  @ApiModelProperty(example = "null", value = "Benefits string for ambulance coverage")
  public String getAmbulance() {
    return ambulance;
  }

  public void setAmbulance(String ambulance) {
    this.ambulance = ambulance;
  }

  public PlanSearchResult benefitsSummaryUrl(String benefitsSummaryUrl) {
    this.benefitsSummaryUrl = benefitsSummaryUrl;
    return this;
  }

   /**
   * Link to the summary of benefits and coverage (SBC) document.
   * @return benefitsSummaryUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to the summary of benefits and coverage (SBC) document.")
  public String getBenefitsSummaryUrl() {
    return benefitsSummaryUrl;
  }

  public void setBenefitsSummaryUrl(String benefitsSummaryUrl) {
    this.benefitsSummaryUrl = benefitsSummaryUrl;
  }

  public PlanSearchResult buyLink(String buyLink) {
    this.buyLink = buyLink;
    return this;
  }

   /**
   * Link to a location to purchase the plan.
   * @return buyLink
  **/
  @ApiModelProperty(example = "null", value = "Link to a location to purchase the plan.")
  public String getBuyLink() {
    return buyLink;
  }

  public void setBuyLink(String buyLink) {
    this.buyLink = buyLink;
  }

  public PlanSearchResult carrierName(String carrierName) {
    this.carrierName = carrierName;
    return this;
  }

   /**
   * Name of the insurance carrier
   * @return carrierName
  **/
  @ApiModelProperty(example = "null", value = "Name of the insurance carrier")
  public String getCarrierName() {
    return carrierName;
  }

  public void setCarrierName(String carrierName) {
    this.carrierName = carrierName;
  }

  public PlanSearchResult childDental(Boolean childDental) {
    this.childDental = childDental;
    return this;
  }

   /**
   * Does the plan provide dental coverage for children?
   * @return childDental
  **/
  @ApiModelProperty(example = "null", value = "Does the plan provide dental coverage for children?")
  public Boolean getChildDental() {
    return childDental;
  }

  public void setChildDental(Boolean childDental) {
    this.childDental = childDental;
  }

  public PlanSearchResult childEyewear(String childEyewear) {
    this.childEyewear = childEyewear;
    return this;
  }

   /**
   * Child eyewear benefits summary
   * @return childEyewear
  **/
  @ApiModelProperty(example = "null", value = "Child eyewear benefits summary")
  public String getChildEyewear() {
    return childEyewear;
  }

  public void setChildEyewear(String childEyewear) {
    this.childEyewear = childEyewear;
  }

  public PlanSearchResult childEyeExam(String childEyeExam) {
    this.childEyeExam = childEyeExam;
    return this;
  }

   /**
   * Child eye exam benefits summary
   * @return childEyeExam
  **/
  @ApiModelProperty(example = "null", value = "Child eye exam benefits summary")
  public String getChildEyeExam() {
    return childEyeExam;
  }

  public void setChildEyeExam(String childEyeExam) {
    this.childEyeExam = childEyeExam;
  }

  public PlanSearchResult customerServicePhoneNumber(String customerServicePhoneNumber) {
    this.customerServicePhoneNumber = customerServicePhoneNumber;
    return this;
  }

   /**
   * Phone number to contact the insurance carrier
   * @return customerServicePhoneNumber
  **/
  @ApiModelProperty(example = "null", value = "Phone number to contact the insurance carrier")
  public String getCustomerServicePhoneNumber() {
    return customerServicePhoneNumber;
  }

  public void setCustomerServicePhoneNumber(String customerServicePhoneNumber) {
    this.customerServicePhoneNumber = customerServicePhoneNumber;
  }

  public PlanSearchResult durableMedicalEquipment(String durableMedicalEquipment) {
    this.durableMedicalEquipment = durableMedicalEquipment;
    return this;
  }

   /**
   * Benefits summary for durable medical equipment
   * @return durableMedicalEquipment
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for durable medical equipment")
  public String getDurableMedicalEquipment() {
    return durableMedicalEquipment;
  }

  public void setDurableMedicalEquipment(String durableMedicalEquipment) {
    this.durableMedicalEquipment = durableMedicalEquipment;
  }

  public PlanSearchResult diagnosticTest(String diagnosticTest) {
    this.diagnosticTest = diagnosticTest;
    return this;
  }

   /**
   * Diagnostic tests benefit summary
   * @return diagnosticTest
  **/
  @ApiModelProperty(example = "null", value = "Diagnostic tests benefit summary")
  public String getDiagnosticTest() {
    return diagnosticTest;
  }

  public void setDiagnosticTest(String diagnosticTest) {
    this.diagnosticTest = diagnosticTest;
  }

  public PlanSearchResult displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Alternate name for the Plan
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "Alternate name for the Plan")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public PlanSearchResult dpRider(Boolean dpRider) {
    this.dpRider = dpRider;
    return this;
  }

   /**
   * Is this a domestic plan?
   * @return dpRider
  **/
  @ApiModelProperty(example = "null", value = "Is this a domestic plan?")
  public Boolean getDpRider() {
    return dpRider;
  }

  public void setDpRider(Boolean dpRider) {
    this.dpRider = dpRider;
  }

  public PlanSearchResult drugFormularyUrl(String drugFormularyUrl) {
    this.drugFormularyUrl = drugFormularyUrl;
    return this;
  }

   /**
   * Link to the summary of drug benefits for the plan
   * @return drugFormularyUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to the summary of drug benefits for the plan")
  public String getDrugFormularyUrl() {
    return drugFormularyUrl;
  }

  public void setDrugFormularyUrl(String drugFormularyUrl) {
    this.drugFormularyUrl = drugFormularyUrl;
  }

  public PlanSearchResult effectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Effective date of coverage.
   * @return effectiveDate
  **/
  @ApiModelProperty(example = "null", value = "Effective date of coverage.")
  public String getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public PlanSearchResult expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Expiration date of coverage.
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", value = "Expiration date of coverage.")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public PlanSearchResult emergencyRoom(String emergencyRoom) {
    this.emergencyRoom = emergencyRoom;
    return this;
  }

   /**
   * Description of costs when visiting the ER
   * @return emergencyRoom
  **/
  @ApiModelProperty(example = "null", value = "Description of costs when visiting the ER")
  public String getEmergencyRoom() {
    return emergencyRoom;
  }

  public void setEmergencyRoom(String emergencyRoom) {
    this.emergencyRoom = emergencyRoom;
  }

  public PlanSearchResult familyDrugDeductible(String familyDrugDeductible) {
    this.familyDrugDeductible = familyDrugDeductible;
    return this;
  }

   /**
   * Deductible for drugs when a family is on the plan.
   * @return familyDrugDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible for drugs when a family is on the plan.")
  public String getFamilyDrugDeductible() {
    return familyDrugDeductible;
  }

  public void setFamilyDrugDeductible(String familyDrugDeductible) {
    this.familyDrugDeductible = familyDrugDeductible;
  }

  public PlanSearchResult familyDrugMoop(String familyDrugMoop) {
    this.familyDrugMoop = familyDrugMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket for drugs when a family is on the plan
   * @return familyDrugMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket for drugs when a family is on the plan")
  public String getFamilyDrugMoop() {
    return familyDrugMoop;
  }

  public void setFamilyDrugMoop(String familyDrugMoop) {
    this.familyDrugMoop = familyDrugMoop;
  }

  public PlanSearchResult familyMedicalDeductible(String familyMedicalDeductible) {
    this.familyMedicalDeductible = familyMedicalDeductible;
    return this;
  }

   /**
   * Deductible when a family is on the plan
   * @return familyMedicalDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible when a family is on the plan")
  public String getFamilyMedicalDeductible() {
    return familyMedicalDeductible;
  }

  public void setFamilyMedicalDeductible(String familyMedicalDeductible) {
    this.familyMedicalDeductible = familyMedicalDeductible;
  }

  public PlanSearchResult familyMedicalMoop(String familyMedicalMoop) {
    this.familyMedicalMoop = familyMedicalMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket when a family is on the plan
   * @return familyMedicalMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket when a family is on the plan")
  public String getFamilyMedicalMoop() {
    return familyMedicalMoop;
  }

  public void setFamilyMedicalMoop(String familyMedicalMoop) {
    this.familyMedicalMoop = familyMedicalMoop;
  }

  public PlanSearchResult fpRider(Boolean fpRider) {
    this.fpRider = fpRider;
    return this;
  }

   /**
   * Is this a family plan?
   * @return fpRider
  **/
  @ApiModelProperty(example = "null", value = "Is this a family plan?")
  public Boolean getFpRider() {
    return fpRider;
  }

  public void setFpRider(Boolean fpRider) {
    this.fpRider = fpRider;
  }

  public PlanSearchResult genericDrugs(String genericDrugs) {
    this.genericDrugs = genericDrugs;
    return this;
  }

   /**
   * Cost for generic drugs
   * @return genericDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost for generic drugs")
  public String getGenericDrugs() {
    return genericDrugs;
  }

  public void setGenericDrugs(String genericDrugs) {
    this.genericDrugs = genericDrugs;
  }

  public PlanSearchResult habilitationServices(String habilitationServices) {
    this.habilitationServices = habilitationServices;
    return this;
  }

   /**
   * Habilitation services benefits summary
   * @return habilitationServices
  **/
  @ApiModelProperty(example = "null", value = "Habilitation services benefits summary")
  public String getHabilitationServices() {
    return habilitationServices;
  }

  public void setHabilitationServices(String habilitationServices) {
    this.habilitationServices = habilitationServices;
  }

  public PlanSearchResult hiosIssuerId(String hiosIssuerId) {
    this.hiosIssuerId = hiosIssuerId;
    return this;
  }

   /**
   * 
   * @return hiosIssuerId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHiosIssuerId() {
    return hiosIssuerId;
  }

  public void setHiosIssuerId(String hiosIssuerId) {
    this.hiosIssuerId = hiosIssuerId;
  }

  public PlanSearchResult homeHealthCare(String homeHealthCare) {
    this.homeHealthCare = homeHealthCare;
    return this;
  }

   /**
   * Home health care benefits summary
   * @return homeHealthCare
  **/
  @ApiModelProperty(example = "null", value = "Home health care benefits summary")
  public String getHomeHealthCare() {
    return homeHealthCare;
  }

  public void setHomeHealthCare(String homeHealthCare) {
    this.homeHealthCare = homeHealthCare;
  }

  public PlanSearchResult hospiceService(String hospiceService) {
    this.hospiceService = hospiceService;
    return this;
  }

   /**
   * Hospice service benefits summary
   * @return hospiceService
  **/
  @ApiModelProperty(example = "null", value = "Hospice service benefits summary")
  public String getHospiceService() {
    return hospiceService;
  }

  public void setHospiceService(String hospiceService) {
    this.hospiceService = hospiceService;
  }

  public PlanSearchResult hsaEligible(Boolean hsaEligible) {
    this.hsaEligible = hsaEligible;
    return this;
  }

   /**
   * Is the plan HSA eligible?
   * @return hsaEligible
  **/
  @ApiModelProperty(example = "null", value = "Is the plan HSA eligible?")
  public Boolean getHsaEligible() {
    return hsaEligible;
  }

  public void setHsaEligible(Boolean hsaEligible) {
    this.hsaEligible = hsaEligible;
  }

  public PlanSearchResult id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Government-issued HIOS plan ID
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Government-issued HIOS plan ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PlanSearchResult imaging(String imaging) {
    this.imaging = imaging;
    return this;
  }

   /**
   * Benefits summary for imaging coverage
   * @return imaging
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for imaging coverage")
  public String getImaging() {
    return imaging;
  }

  public void setImaging(String imaging) {
    this.imaging = imaging;
  }

  public PlanSearchResult inNetworkIds(List<Integer> inNetworkIds) {
    this.inNetworkIds = inNetworkIds;
    return this;
  }

  public PlanSearchResult addInNetworkIdsItem(Integer inNetworkIdsItem) {
    this.inNetworkIds.add(inNetworkIdsItem);
    return this;
  }

   /**
   * List of NPI numbers for Providers passed in who accept this Plan
   * @return inNetworkIds
  **/
  @ApiModelProperty(example = "null", value = "List of NPI numbers for Providers passed in who accept this Plan")
  public List<Integer> getInNetworkIds() {
    return inNetworkIds;
  }

  public void setInNetworkIds(List<Integer> inNetworkIds) {
    this.inNetworkIds = inNetworkIds;
  }

  public PlanSearchResult individualDrugDeductible(String individualDrugDeductible) {
    this.individualDrugDeductible = individualDrugDeductible;
    return this;
  }

   /**
   * Deductible for drugs when an individual is on the plan
   * @return individualDrugDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible for drugs when an individual is on the plan")
  public String getIndividualDrugDeductible() {
    return individualDrugDeductible;
  }

  public void setIndividualDrugDeductible(String individualDrugDeductible) {
    this.individualDrugDeductible = individualDrugDeductible;
  }

  public PlanSearchResult individualDrugMoop(String individualDrugMoop) {
    this.individualDrugMoop = individualDrugMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket for drugs when an individual is on the plan
   * @return individualDrugMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket for drugs when an individual is on the plan")
  public String getIndividualDrugMoop() {
    return individualDrugMoop;
  }

  public void setIndividualDrugMoop(String individualDrugMoop) {
    this.individualDrugMoop = individualDrugMoop;
  }

  public PlanSearchResult individualMedicalDeductible(String individualMedicalDeductible) {
    this.individualMedicalDeductible = individualMedicalDeductible;
    return this;
  }

   /**
   * Deductible when an individual is on the plan
   * @return individualMedicalDeductible
  **/
  @ApiModelProperty(example = "null", value = "Deductible when an individual is on the plan")
  public String getIndividualMedicalDeductible() {
    return individualMedicalDeductible;
  }

  public void setIndividualMedicalDeductible(String individualMedicalDeductible) {
    this.individualMedicalDeductible = individualMedicalDeductible;
  }

  public PlanSearchResult individualMedicalMoop(String individualMedicalMoop) {
    this.individualMedicalMoop = individualMedicalMoop;
    return this;
  }

   /**
   * Maximum out-of-pocket when an individual is on the plan
   * @return individualMedicalMoop
  **/
  @ApiModelProperty(example = "null", value = "Maximum out-of-pocket when an individual is on the plan")
  public String getIndividualMedicalMoop() {
    return individualMedicalMoop;
  }

  public void setIndividualMedicalMoop(String individualMedicalMoop) {
    this.individualMedicalMoop = individualMedicalMoop;
  }

  public PlanSearchResult inpatientBirth(String inpatientBirth) {
    this.inpatientBirth = inpatientBirth;
    return this;
  }

   /**
   * Inpatient birth benefits summary
   * @return inpatientBirth
  **/
  @ApiModelProperty(example = "null", value = "Inpatient birth benefits summary")
  public String getInpatientBirth() {
    return inpatientBirth;
  }

  public void setInpatientBirth(String inpatientBirth) {
    this.inpatientBirth = inpatientBirth;
  }

  public PlanSearchResult inpatientFacility(String inpatientFacility) {
    this.inpatientFacility = inpatientFacility;
    return this;
  }

   /**
   * Cost under the plan for an inpatient facility
   * @return inpatientFacility
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for an inpatient facility")
  public String getInpatientFacility() {
    return inpatientFacility;
  }

  public void setInpatientFacility(String inpatientFacility) {
    this.inpatientFacility = inpatientFacility;
  }

  public PlanSearchResult inpatientMentalHealth(String inpatientMentalHealth) {
    this.inpatientMentalHealth = inpatientMentalHealth;
    return this;
  }

   /**
   * Inpatient mental helath benefits summary
   * @return inpatientMentalHealth
  **/
  @ApiModelProperty(example = "null", value = "Inpatient mental helath benefits summary")
  public String getInpatientMentalHealth() {
    return inpatientMentalHealth;
  }

  public void setInpatientMentalHealth(String inpatientMentalHealth) {
    this.inpatientMentalHealth = inpatientMentalHealth;
  }

  public PlanSearchResult inpatientPhysician(String inpatientPhysician) {
    this.inpatientPhysician = inpatientPhysician;
    return this;
  }

   /**
   * Cost under the plan for an inpatient physician
   * @return inpatientPhysician
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for an inpatient physician")
  public String getInpatientPhysician() {
    return inpatientPhysician;
  }

  public void setInpatientPhysician(String inpatientPhysician) {
    this.inpatientPhysician = inpatientPhysician;
  }

  public PlanSearchResult inpatientSubstance(String inpatientSubstance) {
    this.inpatientSubstance = inpatientSubstance;
    return this;
  }

   /**
   * Inpatient substance abuse benefits summary
   * @return inpatientSubstance
  **/
  @ApiModelProperty(example = "null", value = "Inpatient substance abuse benefits summary")
  public String getInpatientSubstance() {
    return inpatientSubstance;
  }

  public void setInpatientSubstance(String inpatientSubstance) {
    this.inpatientSubstance = inpatientSubstance;
  }

  public PlanSearchResult level(String level) {
    this.level = level;
    return this;
  }

   /**
   * Plan metal grouping (e.g. platinum, gold, silver, etc)
   * @return level
  **/
  @ApiModelProperty(example = "null", value = "Plan metal grouping (e.g. platinum, gold, silver, etc)")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public PlanSearchResult logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Link to a copy of the insurance carrier's logo
   * @return logoUrl
  **/
  @ApiModelProperty(example = "null", value = "Link to a copy of the insurance carrier's logo")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public PlanSearchResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Marketing name of the plan
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Marketing name of the plan")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlanSearchResult nonPreferredBrandDrugs(String nonPreferredBrandDrugs) {
    this.nonPreferredBrandDrugs = nonPreferredBrandDrugs;
    return this;
  }

   /**
   * Cost under the plan for non-preferred brand drugs
   * @return nonPreferredBrandDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for non-preferred brand drugs")
  public String getNonPreferredBrandDrugs() {
    return nonPreferredBrandDrugs;
  }

  public void setNonPreferredBrandDrugs(String nonPreferredBrandDrugs) {
    this.nonPreferredBrandDrugs = nonPreferredBrandDrugs;
  }

  public PlanSearchResult onMarket(Boolean onMarket) {
    this.onMarket = onMarket;
    return this;
  }

   /**
   * Is the plan on-market?
   * @return onMarket
  **/
  @ApiModelProperty(example = "null", value = "Is the plan on-market?")
  public Boolean getOnMarket() {
    return onMarket;
  }

  public void setOnMarket(Boolean onMarket) {
    this.onMarket = onMarket;
  }

  public PlanSearchResult offMarket(Boolean offMarket) {
    this.offMarket = offMarket;
    return this;
  }

   /**
   * Is the plan off-market?
   * @return offMarket
  **/
  @ApiModelProperty(example = "null", value = "Is the plan off-market?")
  public Boolean getOffMarket() {
    return offMarket;
  }

  public void setOffMarket(Boolean offMarket) {
    this.offMarket = offMarket;
  }

  public PlanSearchResult outOfNetworkCoverage(Boolean outOfNetworkCoverage) {
    this.outOfNetworkCoverage = outOfNetworkCoverage;
    return this;
  }

   /**
   * Does this plan provide any out of network coverage?
   * @return outOfNetworkCoverage
  **/
  @ApiModelProperty(example = "null", value = "Does this plan provide any out of network coverage?")
  public Boolean getOutOfNetworkCoverage() {
    return outOfNetworkCoverage;
  }

  public void setOutOfNetworkCoverage(Boolean outOfNetworkCoverage) {
    this.outOfNetworkCoverage = outOfNetworkCoverage;
  }

  public PlanSearchResult outOfNetworkIds(List<Integer> outOfNetworkIds) {
    this.outOfNetworkIds = outOfNetworkIds;
    return this;
  }

  public PlanSearchResult addOutOfNetworkIdsItem(Integer outOfNetworkIdsItem) {
    this.outOfNetworkIds.add(outOfNetworkIdsItem);
    return this;
  }

   /**
   * List of NPI numbers for Providers passed in who do not accept this Plan
   * @return outOfNetworkIds
  **/
  @ApiModelProperty(example = "null", value = "List of NPI numbers for Providers passed in who do not accept this Plan")
  public List<Integer> getOutOfNetworkIds() {
    return outOfNetworkIds;
  }

  public void setOutOfNetworkIds(List<Integer> outOfNetworkIds) {
    this.outOfNetworkIds = outOfNetworkIds;
  }

  public PlanSearchResult outpatientFacility(String outpatientFacility) {
    this.outpatientFacility = outpatientFacility;
    return this;
  }

   /**
   * Benefits summary for outpatient facility coverage
   * @return outpatientFacility
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient facility coverage")
  public String getOutpatientFacility() {
    return outpatientFacility;
  }

  public void setOutpatientFacility(String outpatientFacility) {
    this.outpatientFacility = outpatientFacility;
  }

  public PlanSearchResult outpatientMentalHealth(String outpatientMentalHealth) {
    this.outpatientMentalHealth = outpatientMentalHealth;
    return this;
  }

   /**
   * Benefits summary for outpatient mental health coverage
   * @return outpatientMentalHealth
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient mental health coverage")
  public String getOutpatientMentalHealth() {
    return outpatientMentalHealth;
  }

  public void setOutpatientMentalHealth(String outpatientMentalHealth) {
    this.outpatientMentalHealth = outpatientMentalHealth;
  }

  public PlanSearchResult outpatientPhysician(String outpatientPhysician) {
    this.outpatientPhysician = outpatientPhysician;
    return this;
  }

   /**
   * Benefits summary for outpatient physician coverage
   * @return outpatientPhysician
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for outpatient physician coverage")
  public String getOutpatientPhysician() {
    return outpatientPhysician;
  }

  public void setOutpatientPhysician(String outpatientPhysician) {
    this.outpatientPhysician = outpatientPhysician;
  }

  public PlanSearchResult outpatientSubstance(String outpatientSubstance) {
    this.outpatientSubstance = outpatientSubstance;
    return this;
  }

   /**
   * Outpatient substance abuse benefits summary
   * @return outpatientSubstance
  **/
  @ApiModelProperty(example = "null", value = "Outpatient substance abuse benefits summary")
  public String getOutpatientSubstance() {
    return outpatientSubstance;
  }

  public void setOutpatientSubstance(String outpatientSubstance) {
    this.outpatientSubstance = outpatientSubstance;
  }

  public PlanSearchResult planMarket(String planMarket) {
    this.planMarket = planMarket;
    return this;
  }

   /**
   * Market in which the plan is offered (on_marketplace, shop, etc)
   * @return planMarket
  **/
  @ApiModelProperty(example = "null", value = "Market in which the plan is offered (on_marketplace, shop, etc)")
  public String getPlanMarket() {
    return planMarket;
  }

  public void setPlanMarket(String planMarket) {
    this.planMarket = planMarket;
  }

  public PlanSearchResult planType(String planType) {
    this.planType = planType;
    return this;
  }

   /**
   * Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity)
   * @return planType
  **/
  @ApiModelProperty(example = "null", value = "Category of the plan (e.g. EPO, HMO, PPO, POS, Indemnity)")
  public String getPlanType() {
    return planType;
  }

  public void setPlanType(String planType) {
    this.planType = planType;
  }

  public PlanSearchResult preferredBrandDrugs(String preferredBrandDrugs) {
    this.preferredBrandDrugs = preferredBrandDrugs;
    return this;
  }

   /**
   * Cost under the plan for perferred brand drugs
   * @return preferredBrandDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for perferred brand drugs")
  public String getPreferredBrandDrugs() {
    return preferredBrandDrugs;
  }

  public void setPreferredBrandDrugs(String preferredBrandDrugs) {
    this.preferredBrandDrugs = preferredBrandDrugs;
  }

  public PlanSearchResult prenatalPostnatalCare(String prenatalPostnatalCare) {
    this.prenatalPostnatalCare = prenatalPostnatalCare;
    return this;
  }

   /**
   * Inpatient substance abuse benefits summary
   * @return prenatalPostnatalCare
  **/
  @ApiModelProperty(example = "null", value = "Inpatient substance abuse benefits summary")
  public String getPrenatalPostnatalCare() {
    return prenatalPostnatalCare;
  }

  public void setPrenatalPostnatalCare(String prenatalPostnatalCare) {
    this.prenatalPostnatalCare = prenatalPostnatalCare;
  }

  public PlanSearchResult preventativeCare(String preventativeCare) {
    this.preventativeCare = preventativeCare;
    return this;
  }

   /**
   * Benefits summary for preventative care
   * @return preventativeCare
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for preventative care")
  public String getPreventativeCare() {
    return preventativeCare;
  }

  public void setPreventativeCare(String preventativeCare) {
    this.preventativeCare = preventativeCare;
  }

  public PlanSearchResult premiumSubsidized(BigDecimal premiumSubsidized) {
    this.premiumSubsidized = premiumSubsidized;
    return this;
  }

   /**
   * Cumulative premium amount after subsidy
   * @return premiumSubsidized
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount after subsidy")
  public BigDecimal getPremiumSubsidized() {
    return premiumSubsidized;
  }

  public void setPremiumSubsidized(BigDecimal premiumSubsidized) {
    this.premiumSubsidized = premiumSubsidized;
  }

  public PlanSearchResult premium(BigDecimal premium) {
    this.premium = premium;
    return this;
  }

   /**
   * Cumulative premium amount
   * @return premium
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount")
  public BigDecimal getPremium() {
    return premium;
  }

  public void setPremium(BigDecimal premium) {
    this.premium = premium;
  }

  public PlanSearchResult primaryCarePhysician(String primaryCarePhysician) {
    this.primaryCarePhysician = primaryCarePhysician;
    return this;
  }

   /**
   * Cost under the plan to visit a Primary Care Physician
   * @return primaryCarePhysician
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan to visit a Primary Care Physician")
  public String getPrimaryCarePhysician() {
    return primaryCarePhysician;
  }

  public void setPrimaryCarePhysician(String primaryCarePhysician) {
    this.primaryCarePhysician = primaryCarePhysician;
  }

  public PlanSearchResult rehabilitationServices(String rehabilitationServices) {
    this.rehabilitationServices = rehabilitationServices;
    return this;
  }

   /**
   * Benefits summary for rehabilitation services
   * @return rehabilitationServices
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for rehabilitation services")
  public String getRehabilitationServices() {
    return rehabilitationServices;
  }

  public void setRehabilitationServices(String rehabilitationServices) {
    this.rehabilitationServices = rehabilitationServices;
  }

  public PlanSearchResult serviceAreaId(String serviceAreaId) {
    this.serviceAreaId = serviceAreaId;
    return this;
  }

   /**
   * Foreign key for service area
   * @return serviceAreaId
  **/
  @ApiModelProperty(example = "null", value = "Foreign key for service area")
  public String getServiceAreaId() {
    return serviceAreaId;
  }

  public void setServiceAreaId(String serviceAreaId) {
    this.serviceAreaId = serviceAreaId;
  }

  public PlanSearchResult skilledNursing(String skilledNursing) {
    this.skilledNursing = skilledNursing;
    return this;
  }

   /**
   * Benefits summary for skilled nursing services
   * @return skilledNursing
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for skilled nursing services")
  public String getSkilledNursing() {
    return skilledNursing;
  }

  public void setSkilledNursing(String skilledNursing) {
    this.skilledNursing = skilledNursing;
  }

  public PlanSearchResult specialist(String specialist) {
    this.specialist = specialist;
    return this;
  }

   /**
   * Cost under the plan to visit a specialist
   * @return specialist
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan to visit a specialist")
  public String getSpecialist() {
    return specialist;
  }

  public void setSpecialist(String specialist) {
    this.specialist = specialist;
  }

  public PlanSearchResult specialtyDrugs(String specialtyDrugs) {
    this.specialtyDrugs = specialtyDrugs;
    return this;
  }

   /**
   * Cost under the plan for specialty drugs
   * @return specialtyDrugs
  **/
  @ApiModelProperty(example = "null", value = "Cost under the plan for specialty drugs")
  public String getSpecialtyDrugs() {
    return specialtyDrugs;
  }

  public void setSpecialtyDrugs(String specialtyDrugs) {
    this.specialtyDrugs = specialtyDrugs;
  }

  public PlanSearchResult urgentCare(String urgentCare) {
    this.urgentCare = urgentCare;
    return this;
  }

   /**
   * Benefits summary for urgent care
   * @return urgentCare
  **/
  @ApiModelProperty(example = "null", value = "Benefits summary for urgent care")
  public String getUrgentCare() {
    return urgentCare;
  }

  public void setUrgentCare(String urgentCare) {
    this.urgentCare = urgentCare;
  }

  public PlanSearchResult matchPercentage(Integer matchPercentage) {
    this.matchPercentage = matchPercentage;
    return this;
  }

   /**
   * Percentage of doctors who matched this Plan
   * @return matchPercentage
  **/
  @ApiModelProperty(example = "null", value = "Percentage of doctors who matched this Plan")
  public Integer getMatchPercentage() {
    return matchPercentage;
  }

  public void setMatchPercentage(Integer matchPercentage) {
    this.matchPercentage = matchPercentage;
  }

  public PlanSearchResult perfectMatchPercentage(Integer perfectMatchPercentage) {
    this.perfectMatchPercentage = perfectMatchPercentage;
    return this;
  }

   /**
   * Percentage of employees with 100% match
   * @return perfectMatchPercentage
  **/
  @ApiModelProperty(example = "null", value = "Percentage of employees with 100% match")
  public Integer getPerfectMatchPercentage() {
    return perfectMatchPercentage;
  }

  public void setPerfectMatchPercentage(Integer perfectMatchPercentage) {
    this.perfectMatchPercentage = perfectMatchPercentage;
  }

  public PlanSearchResult employeePremium(BigDecimal employeePremium) {
    this.employeePremium = employeePremium;
    return this;
  }

   /**
   * Cumulative premium amount for employees
   * @return employeePremium
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount for employees")
  public BigDecimal getEmployeePremium() {
    return employeePremium;
  }

  public void setEmployeePremium(BigDecimal employeePremium) {
    this.employeePremium = employeePremium;
  }

  public PlanSearchResult dependentPremium(BigDecimal dependentPremium) {
    this.dependentPremium = dependentPremium;
    return this;
  }

   /**
   * Cumulative premium amount for dependents
   * @return dependentPremium
  **/
  @ApiModelProperty(example = "null", value = "Cumulative premium amount for dependents")
  public BigDecimal getDependentPremium() {
    return dependentPremium;
  }

  public void setDependentPremium(BigDecimal dependentPremium) {
    this.dependentPremium = dependentPremium;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanSearchResult planSearchResult = (PlanSearchResult) o;
    return Objects.equals(this.adultDental, planSearchResult.adultDental) &&
        Objects.equals(this.age29Rider, planSearchResult.age29Rider) &&
        Objects.equals(this.ambulance, planSearchResult.ambulance) &&
        Objects.equals(this.benefitsSummaryUrl, planSearchResult.benefitsSummaryUrl) &&
        Objects.equals(this.buyLink, planSearchResult.buyLink) &&
        Objects.equals(this.carrierName, planSearchResult.carrierName) &&
        Objects.equals(this.childDental, planSearchResult.childDental) &&
        Objects.equals(this.childEyewear, planSearchResult.childEyewear) &&
        Objects.equals(this.childEyeExam, planSearchResult.childEyeExam) &&
        Objects.equals(this.customerServicePhoneNumber, planSearchResult.customerServicePhoneNumber) &&
        Objects.equals(this.durableMedicalEquipment, planSearchResult.durableMedicalEquipment) &&
        Objects.equals(this.diagnosticTest, planSearchResult.diagnosticTest) &&
        Objects.equals(this.displayName, planSearchResult.displayName) &&
        Objects.equals(this.dpRider, planSearchResult.dpRider) &&
        Objects.equals(this.drugFormularyUrl, planSearchResult.drugFormularyUrl) &&
        Objects.equals(this.effectiveDate, planSearchResult.effectiveDate) &&
        Objects.equals(this.expirationDate, planSearchResult.expirationDate) &&
        Objects.equals(this.emergencyRoom, planSearchResult.emergencyRoom) &&
        Objects.equals(this.familyDrugDeductible, planSearchResult.familyDrugDeductible) &&
        Objects.equals(this.familyDrugMoop, planSearchResult.familyDrugMoop) &&
        Objects.equals(this.familyMedicalDeductible, planSearchResult.familyMedicalDeductible) &&
        Objects.equals(this.familyMedicalMoop, planSearchResult.familyMedicalMoop) &&
        Objects.equals(this.fpRider, planSearchResult.fpRider) &&
        Objects.equals(this.genericDrugs, planSearchResult.genericDrugs) &&
        Objects.equals(this.habilitationServices, planSearchResult.habilitationServices) &&
        Objects.equals(this.hiosIssuerId, planSearchResult.hiosIssuerId) &&
        Objects.equals(this.homeHealthCare, planSearchResult.homeHealthCare) &&
        Objects.equals(this.hospiceService, planSearchResult.hospiceService) &&
        Objects.equals(this.hsaEligible, planSearchResult.hsaEligible) &&
        Objects.equals(this.id, planSearchResult.id) &&
        Objects.equals(this.imaging, planSearchResult.imaging) &&
        Objects.equals(this.inNetworkIds, planSearchResult.inNetworkIds) &&
        Objects.equals(this.individualDrugDeductible, planSearchResult.individualDrugDeductible) &&
        Objects.equals(this.individualDrugMoop, planSearchResult.individualDrugMoop) &&
        Objects.equals(this.individualMedicalDeductible, planSearchResult.individualMedicalDeductible) &&
        Objects.equals(this.individualMedicalMoop, planSearchResult.individualMedicalMoop) &&
        Objects.equals(this.inpatientBirth, planSearchResult.inpatientBirth) &&
        Objects.equals(this.inpatientFacility, planSearchResult.inpatientFacility) &&
        Objects.equals(this.inpatientMentalHealth, planSearchResult.inpatientMentalHealth) &&
        Objects.equals(this.inpatientPhysician, planSearchResult.inpatientPhysician) &&
        Objects.equals(this.inpatientSubstance, planSearchResult.inpatientSubstance) &&
        Objects.equals(this.level, planSearchResult.level) &&
        Objects.equals(this.logoUrl, planSearchResult.logoUrl) &&
        Objects.equals(this.name, planSearchResult.name) &&
        Objects.equals(this.nonPreferredBrandDrugs, planSearchResult.nonPreferredBrandDrugs) &&
        Objects.equals(this.onMarket, planSearchResult.onMarket) &&
        Objects.equals(this.offMarket, planSearchResult.offMarket) &&
        Objects.equals(this.outOfNetworkCoverage, planSearchResult.outOfNetworkCoverage) &&
        Objects.equals(this.outOfNetworkIds, planSearchResult.outOfNetworkIds) &&
        Objects.equals(this.outpatientFacility, planSearchResult.outpatientFacility) &&
        Objects.equals(this.outpatientMentalHealth, planSearchResult.outpatientMentalHealth) &&
        Objects.equals(this.outpatientPhysician, planSearchResult.outpatientPhysician) &&
        Objects.equals(this.outpatientSubstance, planSearchResult.outpatientSubstance) &&
        Objects.equals(this.planMarket, planSearchResult.planMarket) &&
        Objects.equals(this.planType, planSearchResult.planType) &&
        Objects.equals(this.preferredBrandDrugs, planSearchResult.preferredBrandDrugs) &&
        Objects.equals(this.prenatalPostnatalCare, planSearchResult.prenatalPostnatalCare) &&
        Objects.equals(this.preventativeCare, planSearchResult.preventativeCare) &&
        Objects.equals(this.premiumSubsidized, planSearchResult.premiumSubsidized) &&
        Objects.equals(this.premium, planSearchResult.premium) &&
        Objects.equals(this.primaryCarePhysician, planSearchResult.primaryCarePhysician) &&
        Objects.equals(this.rehabilitationServices, planSearchResult.rehabilitationServices) &&
        Objects.equals(this.serviceAreaId, planSearchResult.serviceAreaId) &&
        Objects.equals(this.skilledNursing, planSearchResult.skilledNursing) &&
        Objects.equals(this.specialist, planSearchResult.specialist) &&
        Objects.equals(this.specialtyDrugs, planSearchResult.specialtyDrugs) &&
        Objects.equals(this.urgentCare, planSearchResult.urgentCare) &&
        Objects.equals(this.matchPercentage, planSearchResult.matchPercentage) &&
        Objects.equals(this.perfectMatchPercentage, planSearchResult.perfectMatchPercentage) &&
        Objects.equals(this.employeePremium, planSearchResult.employeePremium) &&
        Objects.equals(this.dependentPremium, planSearchResult.dependentPremium);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adultDental, age29Rider, ambulance, benefitsSummaryUrl, buyLink, carrierName, childDental, childEyewear, childEyeExam, customerServicePhoneNumber, durableMedicalEquipment, diagnosticTest, displayName, dpRider, drugFormularyUrl, effectiveDate, expirationDate, emergencyRoom, familyDrugDeductible, familyDrugMoop, familyMedicalDeductible, familyMedicalMoop, fpRider, genericDrugs, habilitationServices, hiosIssuerId, homeHealthCare, hospiceService, hsaEligible, id, imaging, inNetworkIds, individualDrugDeductible, individualDrugMoop, individualMedicalDeductible, individualMedicalMoop, inpatientBirth, inpatientFacility, inpatientMentalHealth, inpatientPhysician, inpatientSubstance, level, logoUrl, name, nonPreferredBrandDrugs, onMarket, offMarket, outOfNetworkCoverage, outOfNetworkIds, outpatientFacility, outpatientMentalHealth, outpatientPhysician, outpatientSubstance, planMarket, planType, preferredBrandDrugs, prenatalPostnatalCare, preventativeCare, premiumSubsidized, premium, primaryCarePhysician, rehabilitationServices, serviceAreaId, skilledNursing, specialist, specialtyDrugs, urgentCare, matchPercentage, perfectMatchPercentage, employeePremium, dependentPremium);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanSearchResult {\n");
    
    sb.append("    adultDental: ").append(toIndentedString(adultDental)).append("\n");
    sb.append("    age29Rider: ").append(toIndentedString(age29Rider)).append("\n");
    sb.append("    ambulance: ").append(toIndentedString(ambulance)).append("\n");
    sb.append("    benefitsSummaryUrl: ").append(toIndentedString(benefitsSummaryUrl)).append("\n");
    sb.append("    buyLink: ").append(toIndentedString(buyLink)).append("\n");
    sb.append("    carrierName: ").append(toIndentedString(carrierName)).append("\n");
    sb.append("    childDental: ").append(toIndentedString(childDental)).append("\n");
    sb.append("    childEyewear: ").append(toIndentedString(childEyewear)).append("\n");
    sb.append("    childEyeExam: ").append(toIndentedString(childEyeExam)).append("\n");
    sb.append("    customerServicePhoneNumber: ").append(toIndentedString(customerServicePhoneNumber)).append("\n");
    sb.append("    durableMedicalEquipment: ").append(toIndentedString(durableMedicalEquipment)).append("\n");
    sb.append("    diagnosticTest: ").append(toIndentedString(diagnosticTest)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    dpRider: ").append(toIndentedString(dpRider)).append("\n");
    sb.append("    drugFormularyUrl: ").append(toIndentedString(drugFormularyUrl)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    emergencyRoom: ").append(toIndentedString(emergencyRoom)).append("\n");
    sb.append("    familyDrugDeductible: ").append(toIndentedString(familyDrugDeductible)).append("\n");
    sb.append("    familyDrugMoop: ").append(toIndentedString(familyDrugMoop)).append("\n");
    sb.append("    familyMedicalDeductible: ").append(toIndentedString(familyMedicalDeductible)).append("\n");
    sb.append("    familyMedicalMoop: ").append(toIndentedString(familyMedicalMoop)).append("\n");
    sb.append("    fpRider: ").append(toIndentedString(fpRider)).append("\n");
    sb.append("    genericDrugs: ").append(toIndentedString(genericDrugs)).append("\n");
    sb.append("    habilitationServices: ").append(toIndentedString(habilitationServices)).append("\n");
    sb.append("    hiosIssuerId: ").append(toIndentedString(hiosIssuerId)).append("\n");
    sb.append("    homeHealthCare: ").append(toIndentedString(homeHealthCare)).append("\n");
    sb.append("    hospiceService: ").append(toIndentedString(hospiceService)).append("\n");
    sb.append("    hsaEligible: ").append(toIndentedString(hsaEligible)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imaging: ").append(toIndentedString(imaging)).append("\n");
    sb.append("    inNetworkIds: ").append(toIndentedString(inNetworkIds)).append("\n");
    sb.append("    individualDrugDeductible: ").append(toIndentedString(individualDrugDeductible)).append("\n");
    sb.append("    individualDrugMoop: ").append(toIndentedString(individualDrugMoop)).append("\n");
    sb.append("    individualMedicalDeductible: ").append(toIndentedString(individualMedicalDeductible)).append("\n");
    sb.append("    individualMedicalMoop: ").append(toIndentedString(individualMedicalMoop)).append("\n");
    sb.append("    inpatientBirth: ").append(toIndentedString(inpatientBirth)).append("\n");
    sb.append("    inpatientFacility: ").append(toIndentedString(inpatientFacility)).append("\n");
    sb.append("    inpatientMentalHealth: ").append(toIndentedString(inpatientMentalHealth)).append("\n");
    sb.append("    inpatientPhysician: ").append(toIndentedString(inpatientPhysician)).append("\n");
    sb.append("    inpatientSubstance: ").append(toIndentedString(inpatientSubstance)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nonPreferredBrandDrugs: ").append(toIndentedString(nonPreferredBrandDrugs)).append("\n");
    sb.append("    onMarket: ").append(toIndentedString(onMarket)).append("\n");
    sb.append("    offMarket: ").append(toIndentedString(offMarket)).append("\n");
    sb.append("    outOfNetworkCoverage: ").append(toIndentedString(outOfNetworkCoverage)).append("\n");
    sb.append("    outOfNetworkIds: ").append(toIndentedString(outOfNetworkIds)).append("\n");
    sb.append("    outpatientFacility: ").append(toIndentedString(outpatientFacility)).append("\n");
    sb.append("    outpatientMentalHealth: ").append(toIndentedString(outpatientMentalHealth)).append("\n");
    sb.append("    outpatientPhysician: ").append(toIndentedString(outpatientPhysician)).append("\n");
    sb.append("    outpatientSubstance: ").append(toIndentedString(outpatientSubstance)).append("\n");
    sb.append("    planMarket: ").append(toIndentedString(planMarket)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    preferredBrandDrugs: ").append(toIndentedString(preferredBrandDrugs)).append("\n");
    sb.append("    prenatalPostnatalCare: ").append(toIndentedString(prenatalPostnatalCare)).append("\n");
    sb.append("    preventativeCare: ").append(toIndentedString(preventativeCare)).append("\n");
    sb.append("    premiumSubsidized: ").append(toIndentedString(premiumSubsidized)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    primaryCarePhysician: ").append(toIndentedString(primaryCarePhysician)).append("\n");
    sb.append("    rehabilitationServices: ").append(toIndentedString(rehabilitationServices)).append("\n");
    sb.append("    serviceAreaId: ").append(toIndentedString(serviceAreaId)).append("\n");
    sb.append("    skilledNursing: ").append(toIndentedString(skilledNursing)).append("\n");
    sb.append("    specialist: ").append(toIndentedString(specialist)).append("\n");
    sb.append("    specialtyDrugs: ").append(toIndentedString(specialtyDrugs)).append("\n");
    sb.append("    urgentCare: ").append(toIndentedString(urgentCare)).append("\n");
    sb.append("    matchPercentage: ").append(toIndentedString(matchPercentage)).append("\n");
    sb.append("    perfectMatchPercentage: ").append(toIndentedString(perfectMatchPercentage)).append("\n");
    sb.append("    employeePremium: ").append(toIndentedString(employeePremium)).append("\n");
    sb.append("    dependentPremium: ").append(toIndentedString(dependentPremium)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

