/*
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
<cost-share>     ::= <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> <tier-limit> "/" <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> "|" <benefit-limit>
<tier>           ::= "In-Network:" | "In-Network-Tier-2:" | "Out-of-Network:"
<opt-num-prefix> ::= "first" <num> <unit> | ""
<unit>           ::= "day(s)" | "visit(s)" | "exam(s)" | "item(s)"
<value>          ::= <ddct_moop> | <copay> | <coinsurance> | <compound> | "unknown" | "Not Applicable"
<compound>       ::= <copay> <deductible> "then" <coinsurance> <deductible> | <copay> <deductible> "then" <copay> <deductible> | <coinsurance> <deductible> "then" <coinsurance> <deductible>
<copay>          ::= "$" <num>
<coinsurace>     ::= <num> "%"
<ddct_moop>      ::= <copay> | "Included in Medical" | "Unlimited"
<opt-per-unit>   ::= "per day" | "per visit" | "per stay" | ""
<deductible>     ::= "before deductible" | "after deductible" | ""
<tier-limit>     ::= ", " <limit> | ""
<benefit-limit>  ::= <limit> | ""
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import model.RequestPlanFindApplicant;
import model.RequestPlanFindDrugPackage;
import model.RequestPlanFindProvider;

import java.io.Serializable;
/**
 * RequestPlanFind
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-26T16:00:18.173-05:00")
public class RequestPlanFind  implements Serializable {
  @JsonProperty("applicants")
  private List<RequestPlanFindApplicant> applicants = new ArrayList<RequestPlanFindApplicant>();

  @JsonProperty("enrollment_date")
  private String enrollmentDate = null;

  @JsonProperty("drug_packages")
  private List<RequestPlanFindDrugPackage> drugPackages = new ArrayList<RequestPlanFindDrugPackage>();

  @JsonProperty("fips_code")
  private String fipsCode = null;

  @JsonProperty("household_income")
  private Integer householdIncome = null;

  @JsonProperty("household_size")
  private Integer householdSize = null;

  @JsonProperty("ids")
  private List<Integer> ids = new ArrayList<Integer>();

  @JsonProperty("market")
  private String market = null;

  @JsonProperty("providers")
  private List<RequestPlanFindProvider> providers = new ArrayList<RequestPlanFindProvider>();

  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("per_page")
  private Integer perPage = null;

  @JsonProperty("sort")
  private String sort = null;

  @JsonProperty("zip_code")
  private String zipCode = null;

  public RequestPlanFind applicants(List<RequestPlanFindApplicant> applicants) {
    this.applicants = applicants;
    return this;
  }

  public RequestPlanFind addApplicantsItem(RequestPlanFindApplicant applicantsItem) {
    this.applicants.add(applicantsItem);
    return this;
  }

   /**
   * Applicants for desired plans.
   * @return applicants
  **/
  @ApiModelProperty(example = "null", value = "Applicants for desired plans.")
  public List<RequestPlanFindApplicant> getApplicants() {
    return applicants;
  }

  public void setApplicants(List<RequestPlanFindApplicant> applicants) {
    this.applicants = applicants;
  }

  public RequestPlanFind enrollmentDate(String enrollmentDate) {
    this.enrollmentDate = enrollmentDate;
    return this;
  }

   /**
   * Date of enrollment
   * @return enrollmentDate
  **/
  @ApiModelProperty(example = "null", value = "Date of enrollment")
  public String getEnrollmentDate() {
    return enrollmentDate;
  }

  public void setEnrollmentDate(String enrollmentDate) {
    this.enrollmentDate = enrollmentDate;
  }

  public RequestPlanFind drugPackages(List<RequestPlanFindDrugPackage> drugPackages) {
    this.drugPackages = drugPackages;
    return this;
  }

  public RequestPlanFind addDrugPackagesItem(RequestPlanFindDrugPackage drugPackagesItem) {
    this.drugPackages.add(drugPackagesItem);
    return this;
  }

   /**
   * National Drug Code Package Id
   * @return drugPackages
  **/
  @ApiModelProperty(example = "null", value = "National Drug Code Package Id")
  public List<RequestPlanFindDrugPackage> getDrugPackages() {
    return drugPackages;
  }

  public void setDrugPackages(List<RequestPlanFindDrugPackage> drugPackages) {
    this.drugPackages = drugPackages;
  }

  public RequestPlanFind fipsCode(String fipsCode) {
    this.fipsCode = fipsCode;
    return this;
  }

   /**
   * County code to determine eligibility
   * @return fipsCode
  **/
  @ApiModelProperty(example = "null", value = "County code to determine eligibility")
  public String getFipsCode() {
    return fipsCode;
  }

  public void setFipsCode(String fipsCode) {
    this.fipsCode = fipsCode;
  }

  public RequestPlanFind householdIncome(Integer householdIncome) {
    this.householdIncome = householdIncome;
    return this;
  }

   /**
   * Total household income.
   * @return householdIncome
  **/
  @ApiModelProperty(example = "null", value = "Total household income.")
  public Integer getHouseholdIncome() {
    return householdIncome;
  }

  public void setHouseholdIncome(Integer householdIncome) {
    this.householdIncome = householdIncome;
  }

  public RequestPlanFind householdSize(Integer householdSize) {
    this.householdSize = householdSize;
    return this;
  }

   /**
   * Number of people living in household.
   * @return householdSize
  **/
  @ApiModelProperty(example = "null", value = "Number of people living in household.")
  public Integer getHouseholdSize() {
    return householdSize;
  }

  public void setHouseholdSize(Integer householdSize) {
    this.householdSize = householdSize;
  }

  public RequestPlanFind ids(List<Integer> ids) {
    this.ids = ids;
    return this;
  }

  public RequestPlanFind addIdsItem(Integer idsItem) {
    this.ids.add(idsItem);
    return this;
  }

   /**
   * List of plan IDs to filter by
   * @return ids
  **/
  @ApiModelProperty(example = "null", value = "List of plan IDs to filter by")
  public List<Integer> getIds() {
    return ids;
  }

  public void setIds(List<Integer> ids) {
    this.ids = ids;
  }

  public RequestPlanFind market(String market) {
    this.market = market;
    return this;
  }

   /**
   * Type of plan to search for.
   * @return market
  **/
  @ApiModelProperty(example = "null", value = "Type of plan to search for.")
  public String getMarket() {
    return market;
  }

  public void setMarket(String market) {
    this.market = market;
  }

  public RequestPlanFind providers(List<RequestPlanFindProvider> providers) {
    this.providers = providers;
    return this;
  }

  public RequestPlanFind addProvidersItem(RequestPlanFindProvider providersItem) {
    this.providers.add(providersItem);
    return this;
  }

   /**
   * List of providers to search for.
   * @return providers
  **/
  @ApiModelProperty(example = "null", value = "List of providers to search for.")
  public List<RequestPlanFindProvider> getProviders() {
    return providers;
  }

  public void setProviders(List<RequestPlanFindProvider> providers) {
    this.providers = providers;
  }

  public RequestPlanFind page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Selected page of paginated response.
   * @return page
  **/
  @ApiModelProperty(example = "null", value = "Selected page of paginated response.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public RequestPlanFind perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * Results per page of response.
   * @return perPage
  **/
  @ApiModelProperty(example = "null", value = "Results per page of response.")
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }

  public RequestPlanFind sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Sort responses by plan field.
   * @return sort
  **/
  @ApiModelProperty(example = "null", value = "Sort responses by plan field.")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public RequestPlanFind zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * 5-digit zip code - this helps determine pricing.
   * @return zipCode
  **/
  @ApiModelProperty(example = "null", value = "5-digit zip code - this helps determine pricing.")
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestPlanFind requestPlanFind = (RequestPlanFind) o;
    return Objects.equals(this.applicants, requestPlanFind.applicants) &&
        Objects.equals(this.enrollmentDate, requestPlanFind.enrollmentDate) &&
        Objects.equals(this.drugPackages, requestPlanFind.drugPackages) &&
        Objects.equals(this.fipsCode, requestPlanFind.fipsCode) &&
        Objects.equals(this.householdIncome, requestPlanFind.householdIncome) &&
        Objects.equals(this.householdSize, requestPlanFind.householdSize) &&
        Objects.equals(this.ids, requestPlanFind.ids) &&
        Objects.equals(this.market, requestPlanFind.market) &&
        Objects.equals(this.providers, requestPlanFind.providers) &&
        Objects.equals(this.page, requestPlanFind.page) &&
        Objects.equals(this.perPage, requestPlanFind.perPage) &&
        Objects.equals(this.sort, requestPlanFind.sort) &&
        Objects.equals(this.zipCode, requestPlanFind.zipCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicants, enrollmentDate, drugPackages, fipsCode, householdIncome, householdSize, ids, market, providers, page, perPage, sort, zipCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestPlanFind {\n");
    
    sb.append("    applicants: ").append(toIndentedString(applicants)).append("\n");
    sb.append("    enrollmentDate: ").append(toIndentedString(enrollmentDate)).append("\n");
    sb.append("    drugPackages: ").append(toIndentedString(drugPackages)).append("\n");
    sb.append("    fipsCode: ").append(toIndentedString(fipsCode)).append("\n");
    sb.append("    householdIncome: ").append(toIndentedString(householdIncome)).append("\n");
    sb.append("    householdSize: ").append(toIndentedString(householdSize)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("    providers: ").append(toIndentedString(providers)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

