/*
 * Vericred API
 * Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://developers.vericred.com) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## SDKs

Our API follows standard REST conventions, so you can use any HTTP client
to integrate with us. You will likely find it easier to use one of our
[autogenerated SDKs](https://github.com/vericred/?query=vericred-),
which we make available for several common programming languages.

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```

## Benefits summary format
Benefit cost-share strings are formatted to capture:
 * Network tiers
 * Compound or conditional cost-share
 * Limits on the cost-share
 * Benefit-specific maximum out-of-pocket costs

**Example #1**
As an example, we would represent [this Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/33602TX0780032.pdf) as:

* **Hospital stay facility fees**:
  - Network Provider: `$400 copay/admit plus 20% coinsurance`
  - Out-of-Network Provider: `$1,500 copay/admit plus 50% coinsurance`
  - Vericred's format for this benefit: `In-Network: $400 before deductible then 20% after deductible / Out-of-Network: $1,500 before deductible then 50% after deductible`

* **Rehabilitation services:**
  - Network Provider: `20% coinsurance`
  - Out-of-Network Provider: `50% coinsurance`
  - Limitations & Exceptions: `35 visit maximum per benefit period combined with Chiropractic care.`
  - Vericred's format for this benefit: `In-Network: 20% after deductible / Out-of-Network: 50% after deductible | limit: 35 visit(s) per Benefit Period`

**Example #2**
In [this other Summary of Benefits &amp; Coverage](https://s3.amazonaws.com/vericred-data/SBC/2017/40733CA0110568.pdf), the **specialty_drugs** cost-share has a maximum out-of-pocket for in-network pharmacies.
* **Specialty drugs:**
  - Network Provider: `40% coinsurance up to a $500 maximum for up to a 30 day supply`
  - Out-of-Network Provider `Not covered`
  - Vericred's format for this benefit: `In-Network: 40% after deductible, up to $500 per script / Out-of-Network: 100%`

**BNF**

Here's a description of the benefits summary string, represented as a context-free grammar:

```
<cost-share>     ::= <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> <tier-limit> "/" <tier> <opt-num-prefix> <value> <opt-per-unit> <deductible> "|" <benefit-limit>
<tier>           ::= "In-Network:" | "In-Network-Tier-2:" | "Out-of-Network:"
<opt-num-prefix> ::= "first" <num> <unit> | ""
<unit>           ::= "day(s)" | "visit(s)" | "exam(s)" | "item(s)"
<value>          ::= <ddct_moop> | <copay> | <coinsurance> | <compound> | "unknown" | "Not Applicable"
<compound>       ::= <copay> <deductible> "then" <coinsurance> <deductible> | <copay> <deductible> "then" <copay> <deductible> | <coinsurance> <deductible> "then" <coinsurance> <deductible>
<copay>          ::= "$" <num>
<coinsurace>     ::= <num> "%"
<ddct_moop>      ::= <copay> | "Included in Medical" | "Unlimited"
<opt-per-unit>   ::= "per day" | "per visit" | "per stay" | ""
<deductible>     ::= "before deductible" | "after deductible" | ""
<tier-limit>     ::= ", " <limit> | ""
<benefit-limit>  ::= <limit> | ""
```


 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import java.io.Serializable;
/**
 * RequestProvidersSearch
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-01-26T16:00:18.173-05:00")
public class RequestProvidersSearch  implements Serializable {
  @JsonProperty("accepts_insurance")
  private Boolean acceptsInsurance = null;

  @JsonProperty("min_score")
  private BigDecimal minScore = null;

  @JsonProperty("network_ids")
  private List<Integer> networkIds = new ArrayList<Integer>();

  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("per_page")
  private Integer perPage = null;

  @JsonProperty("polygon")
  private Integer polygon = null;

  @JsonProperty("radius")
  private Integer radius = null;

  @JsonProperty("search_term")
  private String searchTerm = null;

  @JsonProperty("sort")
  private String sort = null;

  @JsonProperty("sort_seed")
  private Integer sortSeed = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("zip_code")
  private String zipCode = null;

  public RequestProvidersSearch acceptsInsurance(Boolean acceptsInsurance) {
    this.acceptsInsurance = acceptsInsurance;
    return this;
  }

   /**
   * Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true
   * @return acceptsInsurance
  **/
  @ApiModelProperty(example = "null", value = "Limit results to Providers who accept at least one insurance         plan.  Note that the inverse of this filter is not supported and         any value will evaluate to true")
  public Boolean getAcceptsInsurance() {
    return acceptsInsurance;
  }

  public void setAcceptsInsurance(Boolean acceptsInsurance) {
    this.acceptsInsurance = acceptsInsurance;
  }

  public RequestProvidersSearch minScore(BigDecimal minScore) {
    this.minScore = minScore;
    return this;
  }

   /**
   * Minimum search threshold to be included in the results
   * @return minScore
  **/
  @ApiModelProperty(example = "null", value = "Minimum search threshold to be included in the results")
  public BigDecimal getMinScore() {
    return minScore;
  }

  public void setMinScore(BigDecimal minScore) {
    this.minScore = minScore;
  }

  public RequestProvidersSearch networkIds(List<Integer> networkIds) {
    this.networkIds = networkIds;
    return this;
  }

  public RequestProvidersSearch addNetworkIdsItem(Integer networkIdsItem) {
    this.networkIds.add(networkIdsItem);
    return this;
  }

   /**
   * List of Vericred network ids
   * @return networkIds
  **/
  @ApiModelProperty(example = "null", value = "List of Vericred network ids")
  public List<Integer> getNetworkIds() {
    return networkIds;
  }

  public void setNetworkIds(List<Integer> networkIds) {
    this.networkIds = networkIds;
  }

  public RequestProvidersSearch page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number
   * @return page
  **/
  @ApiModelProperty(example = "null", value = "Page number")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public RequestProvidersSearch perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * Number of records to return per page
   * @return perPage
  **/
  @ApiModelProperty(example = "null", value = "Number of records to return per page")
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }

  public RequestProvidersSearch polygon(Integer polygon) {
    this.polygon = polygon;
    return this;
  }

   /**
   * Define a custom search polygon, mutually exclusive with zip_code search
   * @return polygon
  **/
  @ApiModelProperty(example = "null", value = "Define a custom search polygon, mutually exclusive with zip_code search")
  public Integer getPolygon() {
    return polygon;
  }

  public void setPolygon(Integer polygon) {
    this.polygon = polygon;
  }

  public RequestProvidersSearch radius(Integer radius) {
    this.radius = radius;
    return this;
  }

   /**
   * Radius (in miles) to use to limit results
   * @return radius
  **/
  @ApiModelProperty(example = "null", value = "Radius (in miles) to use to limit results")
  public Integer getRadius() {
    return radius;
  }

  public void setRadius(Integer radius) {
    this.radius = radius;
  }

  public RequestProvidersSearch searchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
    return this;
  }

   /**
   * String to search by
   * @return searchTerm
  **/
  @ApiModelProperty(example = "null", value = "String to search by")
  public String getSearchTerm() {
    return searchTerm;
  }

  public void setSearchTerm(String searchTerm) {
    this.searchTerm = searchTerm;
  }

  public RequestProvidersSearch sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * specify sort mode (distance or random)
   * @return sort
  **/
  @ApiModelProperty(example = "null", value = "specify sort mode (distance or random)")
  public String getSort() {
    return sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public RequestProvidersSearch sortSeed(Integer sortSeed) {
    this.sortSeed = sortSeed;
    return this;
  }

   /**
   * Seed value for random sort. Randomly-ordered searches with the same seed return results in consistent order.
   * @return sortSeed
  **/
  @ApiModelProperty(example = "null", value = "Seed value for random sort. Randomly-ordered searches with the same seed return results in consistent order.")
  public Integer getSortSeed() {
    return sortSeed;
  }

  public void setSortSeed(Integer sortSeed) {
    this.sortSeed = sortSeed;
  }

  public RequestProvidersSearch type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Either organization or individual
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Either organization or individual")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RequestProvidersSearch zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Zip Code to search near
   * @return zipCode
  **/
  @ApiModelProperty(example = "null", value = "Zip Code to search near")
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestProvidersSearch requestProvidersSearch = (RequestProvidersSearch) o;
    return Objects.equals(this.acceptsInsurance, requestProvidersSearch.acceptsInsurance) &&
        Objects.equals(this.minScore, requestProvidersSearch.minScore) &&
        Objects.equals(this.networkIds, requestProvidersSearch.networkIds) &&
        Objects.equals(this.page, requestProvidersSearch.page) &&
        Objects.equals(this.perPage, requestProvidersSearch.perPage) &&
        Objects.equals(this.polygon, requestProvidersSearch.polygon) &&
        Objects.equals(this.radius, requestProvidersSearch.radius) &&
        Objects.equals(this.searchTerm, requestProvidersSearch.searchTerm) &&
        Objects.equals(this.sort, requestProvidersSearch.sort) &&
        Objects.equals(this.sortSeed, requestProvidersSearch.sortSeed) &&
        Objects.equals(this.type, requestProvidersSearch.type) &&
        Objects.equals(this.zipCode, requestProvidersSearch.zipCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptsInsurance, minScore, networkIds, page, perPage, polygon, radius, searchTerm, sort, sortSeed, type, zipCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestProvidersSearch {\n");
    
    sb.append("    acceptsInsurance: ").append(toIndentedString(acceptsInsurance)).append("\n");
    sb.append("    minScore: ").append(toIndentedString(minScore)).append("\n");
    sb.append("    networkIds: ").append(toIndentedString(networkIds)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    polygon: ").append(toIndentedString(polygon)).append("\n");
    sb.append("    radius: ").append(toIndentedString(radius)).append("\n");
    sb.append("    searchTerm: ").append(toIndentedString(searchTerm)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    sortSeed: ").append(toIndentedString(sortSeed)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

